/* ============================================================
   NICHOLAS — portfolio data
   Curated to the studio's OWN builds. External clones
   (graphify, ArcReel) deliberately excluded. Jarvis is
   represented as the custom Iron Man assistant only.
   Each project carries a truthful result + a full case write-up
   (problem / approach / outcome / highlights / metrics).
   Generated by build-data.mjs — edit .enriched.json or FIXED there.
   ============================================================ */
window.NS_PROJECTS = [
  {
    "slug": "tickstream",
    "name": "TickStream",
    "category": "Quant / Trading",
    "tagline": "Merging live crypto order books from multiple exchanges into one real-time view",
    "description": "TickStream is a consolidated crypto order book written in Go. It ingests live feeds from Coinbase and Kraken, reconstructs each exchange's order book correctly from snapshots and updates, and merges them into a single unified view. This allows traders to see the best available prices across connected exchanges in real-time.",
    "problem": "For cryptocurrency traders, having a unified view of order books from multiple exchanges is essential for making informed decisions. However, each exchange sends data in its own format, messages arrive out of order, and gaps can occur due to network issues. Merging these feeds into a consistent, real-time view without errors or delays is technically challenging, as it requires handling data integrity, synchronization, and concurrency without blocking readers.",
    "approach": "TickStream uses a single writer engine that processes order-book updates from each exchange in a dedicated goroutine. Each feed decodes and normalizes messages, sending them to the engine via a bounded channel. The engine applies updates to per-venue books, verifies integrity using checksums (like CRC32 for Kraken), and resyncs from fresh snapshots on failures. It consolidates the books into a single best bid and offer. The system publishes a new immutable snapshot after each update, allowing any number of readers to access the data wait-free via an atomic pointer load. This design avoids locks and ensures readers never block the writer. Key challenges included ensuring snapshot immutability (not reusing memory across publishes), handling full channels without blocking (dropping frames and resyncing), and maintaining correctness during high-throughput scenarios.",
    "outcome": "TickStream is built and tested, with measured end-to-end apply latency of 7.4 µs at p50 and a wait-free read path at 41 ns. It has been verified with concurrent assertion tests for immutability, checksum tests, and a full apply-semantics matrix. The system is open-sourced on GitHub, demonstrating a working implementation of a consolidated order book in Go.",
    "highlights": [
      "Wait-free read path using atomic pointer loads, with p50 latency of 41 ns",
      "Immutable snapshot publication ensures readers never see torn data",
      "Bounded channel hand-off drops frames on full buffer to prevent writer blocking",
      "Checksum verification (CRC32 for Kraken) triggers full resync on mismatch",
      "Concurrent assertion tests enforce snapshot immutability invariant",
      "Measured end-to-end apply latency with coordinated-omission-aware benchmarks"
    ],
    "metrics": [
      {
        "value": "7.4 µs",
        "label": "median end-to-end apply latency"
      },
      {
        "value": "41 ns",
        "label": "median wait-free book read"
      },
      {
        "value": "200,000",
        "label": "samples behind the measurement"
      }
    ],
    "result": "A working consolidated order book with measured latencies, built in Go and open-sourced",
    "techStack": [
      "Go",
      "WebSocket",
      "HdrHistogram"
    ],
    "status": "Built",
    "url": "https://github.com/nyaungnicholas-wq/tickstream",
    "tier": "flagship"
  },
  {
    "slug": "equity-direction-study",
    "name": "Equity Direction Study",
    "category": "Quant / Trading",
    "tagline": "Honest evaluation of machine-learning equity direction forecasts",
    "description": "A quantitative research study examining whether gradient-boosted trees can predict five-day equity price direction better than logistic regression, using technical features on five liquid U.S. instruments. The contribution lies in its rigorous evaluation with walk-forward validation, threshold analysis, transaction costs, and naive baselines, revealing that the apparent edge does not survive scrutiny.",
    "problem": "In quantitative finance, machine-learning models often show promising backtest results, but these can be misleading due to overfitting, improper validation, and ignoring transaction costs. Investors need a way to distinguish real predictive power from statistical noise, especially in efficient markets where edges are hard to find and even harder to sustain.",
    "approach": "The study pre-specifies two models—logistic regression and XGBoost—to predict five-day direction from eleven technical features on five instruments. It uses purged expanding-window cross-validation through 2024 with a five-date purge gap, then evaluates on an untouched 2025 holdout. Hard work included implementing moving-block bootstrap for uncertainty, decomposing the simulated portfolio return to show it relies on three periods, and calculating statistical power to reveal the design was underpowered by roughly a factor of five. The approach follows a rigorous backtesting protocol to ensure honest reporting.",
    "outcome": "The study concludes with negative results: neither model achieved a ROC-AUC above 0.5 on the holdout, both were beaten by naive baselines, and the economic return was an artifact of three days. The comparison between models is inconclusive due to insufficient statistical power. The contribution is a documented pre-specified negative result and a demonstration of honest evaluation techniques.",
    "highlights": [
      "Pre-specified models with an untouched 2025 holdout year to prevent overfitting",
      "Both models performed worse than an always-up rule with statistical significance",
      "Economic return decomposed to show 95.4% of excess return came from just three periods",
      "Power calculation revealed the design was underpowered by roughly a factor of five",
      "Adherence to the Arnott-Harvey-Markowitz backtesting protocol for honest evaluation",
      "Comparison includes proper scoring rules and naive baselines, not just accuracy"
    ],
    "metrics": [
      {
        "value": "0.460",
        "label": "holdout ROC-AUC — worse than a coin flip"
      },
      {
        "value": "95.4%",
        "label": "of the excess return came from three days"
      },
      {
        "value": "28.3 pts",
        "label": "smallest gap the design could have detected"
      }
    ],
    "result": "No predictive edge found; apparent economic result is an artifact of three days and does not survive scrutiny",
    "techStack": [
      "Python",
      "XGBoost",
      "pandas",
      "scikit-learn"
    ],
    "status": "Built",
    "url": null,
    "tier": "standard"
  },
  {
    "slug": "flow",
    "name": "Flow",
    "category": "Developer Tool",
    "tagline": "Local voice dictation that types cleaned-up text into any focused window",
    "description": "A self-hosted voice dictation tool: hold a hotkey, talk, release. Speech is transcribed on the machine's own CPU with faster-whisper, a language-model pass strips filler words and fixes punctuation, and the cleaned text is typed straight into whatever window has focus — Slack, an editor, an email. A local replacement for a paid dictation subscription, with the audio never leaving the box.",
    "problem": "Many voice dictation tools require paid subscriptions and send audio to cloud servers, raising privacy concerns for users who dictate frequently. A local solution is needed that maintains accuracy and convenience without relying on internet connectivity or sharing personal speech data with external services.",
    "approach": "Flow uses pynput for global hotkey listening, where holding Ctrl+Alt records audio via sounddevice. On release, faster-whisper transcribes the audio locally on CPU with int8 compute and configurable threads. The raw text is sent to a local OmniRoute gateway for cleanup with a LLM (e.g., gemini-3.1-flash-lite), which corrects punctuation and removes fillers. If the LLM fails or is slow, it falls back to regex-based filler stripping. The cleaned text is injected by copying to clipboard and simulating Ctrl+V, ensuring compatibility with any application. The entire pipeline runs on a worker thread to prevent keyboard freezing during transcription, and truncated LLM responses are discarded to avoid partial text.",
    "outcome": "The tool is fully functional and runs locally with all processing on the machine. It includes end-to-end checks for audio capture, transcription, polishing, and injection. Custom dictionaries and snippets can be configured, and it handles edge cases like LLM unavailability by falling back to offline cleanup.",
    "highlights": [
      "Speech recognition runs on the machine's own CPU — the recorded audio never leaves the box",
      "Two hotkey modes — dictate at the cursor, or rewrite the text currently selected",
      "LLM cleanup pass corrects punctuation and removes filler words",
      "Injects text into any application via clipboard and keyboard simulation",
      "Worker thread pipeline prevents keyboard freezing during transcription",
      "Fallback to regex filler stripping if LLM is unavailable or slow"
    ],
    "metrics": [
      {
        "value": "0",
        "label": "recorded audio that leaves the machine"
      },
      {
        "value": "2",
        "label": "hotkey modes — dictate and rewrite"
      },
      {
        "value": "4",
        "label": "standalone checks, one end-to-end"
      }
    ],
    "result": "Running locally as a replacement for a paid dictation subscription — audio stays on the machine",
    "techStack": [
      "Python",
      "faster-whisper",
      "pynput",
      "sounddevice",
      "pyperclip"
    ],
    "status": "Built",
    "url": null,
    "tier": "standard"
  },
  {
    "slug": "ae-to-remotion",
    "name": "AE to Remotion",
    "category": "Developer Tool",
    "tagline": "Motion graphics written as code instead of dragged on a timeline",
    "description": "A translation layer that maps After Effects concepts onto Remotion, so motion graphics can be written as React components instead of hand-animated in a timeline. Video becomes something that can be version-controlled, diffed, reviewed, parameterised, and re-rendered by a machine on a schedule. An eight-second showcase composition is built entirely on the toolkit.",
    "problem": "Motion graphics normally live inside a visual timeline, where every animation is hand-tweaked in a binary project file. That file cannot be diffed, reviewed, or generated — which makes changing a single word across fifty videos a manual job, and makes automated rendering impossible. Moving that work into code sounds obvious until you try it: the timeline concepts an editor relies on have no direct equivalent in a React renderer.",
    "approach": "The toolkit rebuilds the After Effects vocabulary as React primitives. Null objects become components that apply a transform to their children and publish the composed world transform on context, which is what makes inverse parenting possible — a child that deliberately ignores its parent reads that context and applies the inverse. Adjustment layers use a backdrop-filter on a sibling painted above the layers it grades, so the effect applies to everything beneath it without wrapping it. Track mattes are SVG masks driving a CSS mask-image, supporting alpha, luma and inverted-luma modes, with the inverted case handled by a white backing rectangle and a difference blend. Keyframes take the same four bezier control values as the After Effects speed graph, and overshoot presets use a real spring solver rather than a baked curve.",
    "outcome": "Built and rendering. The showcase composition outputs an eight-second intro at 1920×1080 and 60fps — 600 frames, roughly four minutes of render time — and the project type-checks clean. The concept map in the README states plainly which After Effects features do not carry over, including 3D layers, rather than leaving the gaps to be discovered mid-project.",
    "highlights": [
      "Null objects and parenting rebuilt as React context, including deliberate inverse parenting",
      "Adjustment layers implemented with backdrop-filter on a sibling painted above the graded layers",
      "Track mattes via SVG masks in alpha, luma and inverted-luma modes",
      "Keyframes take the same four bezier control values as the After Effects speed graph",
      "Overshoot and bounce use a real spring solver rather than a baked easing curve",
      "Every animation is frame-relative, so a sequence can be retimed without re-keying it"
    ],
    "metrics": [
      {
        "value": "1920×1080",
        "label": "showcase render, 60fps"
      },
      {
        "value": "600",
        "label": "frames driven entirely by code"
      },
      {
        "value": "~4 min",
        "label": "to render the full showcase"
      }
    ],
    "result": "A working translation layer — the showcase intro is rendered entirely from React code",
    "techStack": [
      "React",
      "Remotion",
      "TypeScript",
      "SVG"
    ],
    "status": "Built",
    "url": null,
    "tier": "standard"
  },
  {
    "slug": "1042s-organizer",
    "name": "1042-S Organizer",
    "category": "Developer Tool",
    "tagline": "Turning a 1,000-page tax PDF into one clean file per recipient",
    "description": "An Adobe Acrobat JavaScript tool that reads a single massive IRS filing PDF, works out which recipient each page belongs to, and splits it into one correctly-named, correctly-ordered file per person — with every form still paired to its instruction page. Built for a real client and running on their machine.",
    "problem": "A tax preparer receives one enormous PDF containing hundreds of IRS 1042-S forms — plus 1099s, W-2s and annual 1042s — for dozens of different recipients, shuffled together and each paired with an instruction page. Splitting and sorting it by hand is hours of error-prone work every filing season, and a misfiled form means sending one client another client's tax data.",
    "approach": "The tool runs inside Adobe Acrobat as pure Acrobat JavaScript, so it needs no installation and no data ever leaves the client's machine. It reads the text off each page, identifies which IRS form type it is, extracts the recipient from Box 13a, keeps every form glued to its instruction page, then writes one alphabetically-sorted file per recipient plus a CSV manifest. Because Acrobat's scripting engine is single-threaded and freezes the UI on long loops, the runner is chunked so Acrobat stays responsive across a thousand-plus pages.",
    "outcome": "Shipped and proven on the client's own Acrobat installation — four separate bugs reported from the client's real environment were each fixed and then locked down with a permanent regression test. A demo harness downloads the genuine IRS forms from irs.gov, stamps real recipient names into Box 13a, shuffles the pages, and verifies the organiser reconstructs every file correctly with no page lost.",
    "highlights": [
      "Runs entirely inside Adobe Acrobat — no install, no upload, tax data never leaves the machine",
      "Identifies 1042-S, 1099, W-2 and 1042 pages and groups every form a recipient has into one file",
      "Keeps each form paired with its instruction page so nothing is separated in the split",
      "Chunked runner keeps Acrobat responsive instead of freezing on long documents",
      "CSV manifest export guarded against spreadsheet formula injection",
      "Filename sanitisation strips control characters and normalises paths to prevent stray writes"
    ],
    "metrics": [
      {
        "value": "101",
        "label": "assertions across 5 test suites"
      },
      {
        "value": "600",
        "label": "randomised documents fuzz-tested"
      },
      {
        "value": "20/20",
        "label": "names read off the real IRS form"
      }
    ],
    "result": "Shipped to a paying client and proven on their Acrobat — open-sourced with a full test suite",
    "techStack": [
      "Acrobat JavaScript",
      "Node",
      "pdf-lib",
      "pdfjs-dist"
    ],
    "status": "Live",
    "url": "https://github.com/nyaungnicholas-wq/1042s-organizer",
    "tier": "flagship"
  },
  {
    "slug": "throughline",
    "name": "Throughline",
    "category": "SaaS Product",
    "tagline": "Delegate the work, track it, approve it — without the spreadsheet",
    "description": "A multi-tenant work-management platform built around one loop most tools ignore: a manager delegates a piece of work, the assignee moves it forward, and someone with authority approves it. Boards render as table, kanban, calendar or timeline, all projected from a single snapshot of the data.",
    "problem": "General project tools track that work exists but not who owes what to whom. The moment a team needs real delegation with an approval step, the process leaks into spreadsheets and chat — and nothing stops a person from quietly approving their own work.",
    "approach": "Delegation is modelled as an explicit seven-state machine with a single mutator function, so every transition is validated in one place and no-self-approval is enforced for every role including owners. Flexible per-board columns use a typed entity-attribute-value model rather than dynamic schema changes. Tenant isolation runs through one authorisation chokepoint, backed by a custom ESLint rule that fails the build if a component reaches for the database directly. The same code runs on an embedded Postgres locally and a hosted Postgres in production, with migrations serialised by an advisory lock so cold-starting instances can't race.",
    "outcome": "Feature-complete and green across typecheck, lint, tests and production build. Runs with zero configuration locally — install, start, and a dev quick-login drops you into a seeded two-organisation demo.",
    "highlights": [
      "Seven-state delegation machine with no-self-approval enforced for every role",
      "Table, kanban, calendar and timeline views all projected from one board snapshot",
      "Multi-tenant isolation through a single authorisation chokepoint, guarded by a custom ESLint rule",
      "Typed EAV model gives per-board custom columns without dynamic schema migrations",
      "Dual database driver — embedded Postgres locally, hosted Postgres in production, one codebase",
      "Advisory-lock migrations stop cold-starting serverless instances racing each other"
    ],
    "metrics": [
      {
        "value": "7",
        "label": "state delegation machine, one mutator"
      },
      {
        "value": "31",
        "label": "routes across the app"
      },
      {
        "value": "0",
        "label": "config needed to run it locally"
      }
    ],
    "result": "Feature-complete — build, lint, typecheck and full test suite all green",
    "techStack": [
      "Next.js 16",
      "React 19",
      "TypeScript",
      "Drizzle ORM",
      "Postgres",
      "Tailwind v4"
    ],
    "status": "Built",
    "url": null,
    "tier": "flagship"
  },
  {
    "slug": "taxlens",
    "name": "TaxLens",
    "category": "AI Agent",
    "tagline": "Cross-border tax answers that cite their own sources",
    "description": "A grounded AI assistant sitting on top of a purpose-built cross-border tax knowledge base covering 147 countries. It answers withholding-tax and treaty questions by retrieving from verified data rather than generating from memory, and shows the corridor data behind every answer.",
    "problem": "Cross-border withholding tax is exactly the kind of question a general chatbot answers confidently and wrongly. The real rates live in treaty tables that differ per country pair, per income type, and change over time — so an answer without a verifiable source behind it is worse than no answer.",
    "approach": "Rather than trusting a model's recall, the system ingests official treaty withholding data into a local knowledge base, marks each country corridor with how well-sourced it is, and only lets the assistant answer from what it can retrieve. Ingesting the OECD treaty withholding dataset added tens of thousands of verified rows and promoted roughly six hundred non-US corridors from single-source to verified. A global explorer lets you browse all 147 countries directly, and answers export to a PDF memo.",
    "outcome": "Live and publicly reachable, running as a containerised app on a free hosting tier with a self-healing database bootstrap that re-seeds itself on integrity failure or version change.",
    "highlights": [
      "147-country sortable tax explorer built from a real territories dataset",
      "34,819 OECD treaty withholding rows ingested and reconciled",
      "~600 country corridors promoted from single-source to verified",
      "Answers are grounded in retrieved data and exportable as a PDF memo",
      "Holding-structure optimiser and follow-and-alert on corridors you care about",
      "Self-healing container bootstrap re-seeds the database on integrity failure"
    ],
    "metrics": [
      {
        "value": "147",
        "label": "countries in the explorer"
      },
      {
        "value": "34,819",
        "label": "treaty withholding rows ingested"
      },
      {
        "value": "86/86",
        "label": "grounding evaluation passed"
      }
    ],
    "result": "Live and public — grounded answers across 147 countries, sources shown",
    "techStack": [
      "Python",
      "FastAPI",
      "SQLite",
      "React",
      "Docker"
    ],
    "status": "Live",
    "url": "https://n1ch0las-taxlens.hf.space",
    "tier": "flagship"
  },
  {
    "slug": "quant-suite",
    "name": "Quant Suite",
    "category": "Quant / Trading",
    "tagline": "Describe a strategy in English, get a reproducible backtest",
    "description": "A three-application finance suite sharing one foundation: CopilotQuant turns a plain-English strategy description into a typed specification and backtests it, RiskLens analyses portfolio risk, and FilingMind reads company filings. Built from adversarially-reviewed specifications rather than improvised.",
    "problem": "Most backtesting tools force you to write code before you can test an idea, and most give you a different answer if you run them twice. Neither is acceptable if the number is going to inform a decision.",
    "approach": "A monorepo splits the interface from the computation: a TypeScript web application handles parsing, storage and presentation, while a Python service owns the actual backtest engine, written in plain pandas and numpy so the maths stays auditable. Natural language is parsed into a typed strategy specification — a validated object, not a prompt — which is what actually gets executed. Determinism is enforced by keying the data generator off a hash of the seed and symbol, so the same specification produces a byte-identical result run after run.",
    "outcome": "All three units built and verified end to end in the browser: login, parse a strategy from English, save it, run the backtest through the live Python service, and read the metrics, equity curve and fill blotter. Reproducibility proven by two runs returning identical figures to six decimal places.",
    "highlights": [
      "English strategy description parsed into a typed, validated specification before execution",
      "Backtest engine in pure pandas/numpy so every calculation is auditable",
      "Byte-identical results across repeated runs — determinism proven, not assumed",
      "Dashboard with metrics, equity-vs-benchmark, drawdown and a full fill blotter",
      "Grounded explanations of results generated from the actual run data",
      "Built from adversarially-reviewed specs with pinned architectural decisions"
    ],
    "metrics": [
      {
        "value": "331",
        "label": "tests green across Python and TypeScript"
      },
      {
        "value": "3",
        "label": "applications on one shared foundation"
      },
      {
        "value": "2",
        "label": "runs, byte-identical output"
      }
    ],
    "result": "All three units built and browser-verified — reproducibility proven to six decimals",
    "techStack": [
      "Next.js 16",
      "React 19",
      "TypeScript",
      "Python",
      "FastAPI",
      "pandas"
    ],
    "status": "Built",
    "url": null,
    "tier": "flagship"
  },
  {
    "slug": "lotline",
    "name": "Lotline",
    "category": "SaaS Product",
    "tagline": "What a property is worth, costs to own, and costs to fix",
    "description": "A property-intelligence application for real-estate agents, investors and developers. It pulls from eleven live data sources — including tax-defaulted property rolls and trustee, sheriff and probate notices — to answer the three questions that actually decide a deal.",
    "problem": "The data that tells you whether a property is a real opportunity is scattered across county tax rolls, legal notice publications and listing feeds, much of it published as PDFs designed for human eyes rather than software.",
    "approach": "A source engine normalises eleven feeds behind one interface, with purpose-written PDF and HTML adapters for the distress signals that are only published as scanned county documents. The interface is dark-first and deliberately dense — closer to a terminal than a consumer app — with five interactive pillars covering comparables, cost of ownership, and renovation cost.",
    "outcome": "Deployed and reachable, with the AI layer running live. Roughly sixty pages across twenty-nine routes, full test suite green, typecheck and lint clean.",
    "highlights": [
      "Eleven live data sources normalised behind a single engine interface",
      "Custom PDF and HTML adapters extract distress signals from county documents",
      "Tax-defaulted rolls plus trustee, sheriff and probate notices in one view",
      "Five interactive pillars covering comparables, ownership cost and renovation cost",
      "Dark-first dense interface built for professionals, not casual browsers"
    ],
    "metrics": [
      {
        "value": "11",
        "label": "live data sources"
      },
      {
        "value": "29",
        "label": "routes, ~60 pages"
      },
      {
        "value": "49/49",
        "label": "tests green"
      }
    ],
    "result": "Deployed and live with eleven data sources feeding it",
    "techStack": [
      "Next.js 16",
      "React 19",
      "TypeScript",
      "Tailwind v4",
      "Recharts"
    ],
    "status": "Live",
    "url": "https://lotline-nine.vercel.app",
    "tier": "standard"
  },
  {
    "slug": "creatorledger",
    "name": "CreatorLedger",
    "category": "SaaS Product",
    "tagline": "What creators actually keep after tax",
    "description": "A financial back-office aimed at creators earning across several platforms at once. The first public piece is a free calculator that takes multi-platform income and returns real profit and the quarterly tax to set aside — shipped as a validation asset before building the full product.",
    "problem": "A creator earning from four platforms has no single number for what they actually keep. Self-employment tax, the half-SE deduction and irregular income make the arithmetic genuinely hard, and getting it wrong shows up as a surprise tax bill.",
    "approach": "Rather than building the product and hoping, the idea went through a validation pass that killed seven other consumer-finance concepts on licensing traps, entrenched free incumbents, or one-off revenue. The survivor was tested with the cheapest possible artefact: a single static page with a working calculator that computes federal brackets, standard deduction, self-employment tax and the half-SE deduction entirely client-side, with an email capture attached.",
    "outcome": "Live and public on free hosting, functioning as a demand test rather than a launch — the calculator is genuinely useful on its own, which is what earns the email address.",
    "highlights": [
      "Seven competing product ideas tested and eliminated before committing to this one",
      "Free calculator covering federal brackets, standard deduction and self-employment tax",
      "Runs entirely client-side — no income figures are ever transmitted",
      "Shipped as a demand test first, product second"
    ],
    "metrics": [
      {
        "value": "7",
        "label": "ideas eliminated before choosing this one"
      },
      {
        "value": "0",
        "label": "income data leaves the browser"
      }
    ],
    "result": "Live as a demand test — a working calculator earning the signup",
    "techStack": [
      "HTML",
      "CSS",
      "Vanilla JS"
    ],
    "status": "Live",
    "url": "https://nyaungnicholas-wq.github.io/creatorledger",
    "tier": "standard"
  },
  {
    "slug": "nova-studio",
    "name": "NOVA Studio",
    "category": "AI Agent",
    "tagline": "One operator running social content for many brands",
    "description": "A multi-tenant command center for social video: an idea becomes a script, the script becomes a cinematic AI-generated reel, the reel gets per-platform captions, and the whole thing schedules out to Reels, TikTok and Shorts. Currently runs in mock and dry-run mode — nothing is published and no credits are spent at rest.",
    "problem": "Running short-form video for several brands means repeating the same chain — idea, script, footage, captions, per-platform copy, scheduling — over and over, with the context for each brand held in someone's head.",
    "approach": "The core of the system is a prompt engine that turns a brief into structured, preset-driven generation instructions rather than freeform text, so output stays consistent across runs and across brands. A Python API owns generation and scheduling; a separate React front end is the operator's console. Every external side effect is behind a live/dry-run flag that defaults to off.",
    "outcome": "Verified end to end in mock and dry-run mode: the full chain runs, produces its artefacts, and stops short of publishing. Deliberately left unarmed until the pipeline is trusted.",
    "highlights": [
      "Multi-tenant — one operator, several brands, isolated context each",
      "Preset-driven prompt engine for consistent generation instead of freeform prompting",
      "Every publishing side effect behind a dry-run flag that defaults to off",
      "Verified end to end without spending generation credits or posting anything"
    ],
    "metrics": [
      {
        "value": "3",
        "label": "tenants configured"
      },
      {
        "value": "0",
        "label": "credits spent at rest"
      }
    ],
    "result": "Full pipeline verified in dry-run — deliberately not armed to publish yet",
    "techStack": [
      "FastAPI",
      "Python",
      "React 19",
      "Vite",
      "Tailwind v4"
    ],
    "status": "Prototype",
    "url": null,
    "tier": "standard"
  },
  {
    "slug": "grownet",
    "name": "GrowNet",
    "category": "SaaS Product",
    "tagline": "One funnel that catches leads and starts conversations",
    "description": "GrowNet is one growth platform that runs inbound lead capture and outbound cold outreach side by side for small teams. It sits on a spine-first data model: one person is exactly one record, so the two channels can never work the same contact at once.",
    "problem": "Teams that run inbound and outbound on separate tools waste leads. The same person gets cold-emailed while a nurture sequence is already running. No system owns the contact, so the channels step on each other and the prospect ends up with a confusing double-touch.",
    "approach": "GrowNet came from merging two earlier products, LeadNet (inbound) and ReachNet (outbound), into one contact-spine data model where each person is a single record both channels read and write. The interference problem gets solved in the database rather than the UI. A single-active-automation lock means a contact can have at most one running automation, so a nurture sequence and a cold campaign can never fire on the same person at the same time. An import warm-exclusion guard catches the correlation case right at ingestion: newly imported prospects are held back from outbound if they already exist as warm inbound contacts. On top of the unified funnel sits a Growth Advisor that reads the whole pipeline and surfaces correlation-aware next moves. An onboarding agent reads a company website to pre-write copy and set up sender identity. The design was worked out council-first before any building started. Stack: Next.js, React 19, TypeScript, Drizzle ORM, Postgres, Tailwind, with an indigo/emerald/sky three-channel UI.",
    "outcome": "Built and verified. The full inbound to outbound loop was run twice as the client, both passes green, and the next build passed. Status is Built, not yet deployed.",
    "highlights": [
      "Merges LeadNet inbound and ReachNet outbound into one contact-spine data model",
      "Single-active-automation lock, enforced in the database, blocks channel collisions",
      "Import warm-exclusion guard holds back prospects who are already warm inbound contacts",
      "Inbound capture forms and an outbound campaign dispatcher live in one interface",
      "Growth Advisor reads the whole funnel and surfaces correlation-aware next moves",
      "Onboarding agent reads a website to pre-write copy and set up sender identity"
    ],
    "metrics": [
      {
        "value": "1",
        "label": "record per person (contact spine)"
      },
      {
        "value": "2",
        "label": "channels, one lock"
      },
      {
        "value": "2x",
        "label": "full-loop client passes, both green"
      }
    ],
    "result": "Full inbound → outbound loop verified twice as a client — both passes green",
    "techStack": [
      "Next.js",
      "React 19",
      "TypeScript",
      "Drizzle ORM",
      "Postgres",
      "Tailwind"
    ],
    "status": "Built",
    "url": null,
    "tier": "flagship"
  },
  {
    "slug": "leadnet",
    "name": "LeadNet",
    "category": "SaaS Product",
    "tagline": "Speed-to-lead capture for local small businesses",
    "description": "A multi-tenant lead-capture SaaS for local small businesses. It catches every form submission, fires instant alerts and branded auto-replies, then nurtures leads through multi-step email sequences. It's built for realtors, contractors, and attorneys who win by answering fast. Delivery is only confirmed once an alert actually succeeds.",
    "problem": "Local businesses lose deals when they answer leads too slowly. Most capture tools make it worse: they quietly drop submissions when an alert fails or when billing lapses. The lead that came in while you were on a job site is usually the one you needed most. And a tool that stops capturing the moment a card expires turns a billing hiccup into lost revenue.",
    "approach": "Leads arrive through an embeddable widget or a headless endpoint. On every submission the system fans out to configured sinks (Google Sheets, Brevo, HubSpot, or a webhook), with secrets held under AES-256 encryption. It only confirms delivery to the submitter once an alert has actually succeeded, so a silent failure can't masquerade as a saved lead. Five vertical templates pre-shape forms and copy per industry, and a setup agent reads the company website to auto-extract business info during onboarding. The nurture engine drives multi-step email sequences that auto-stop the moment a human reply lands. On top of the speed-to-lead inbox sit the reply engine and inbound advisor. The defining design decision is that capture is always-on while billing is decoupled from it. An operator can manually suspend an account, which locks the dashboard but never stops capture. Leads keep flowing into a vault that the customer pays to access, with a 7-day grace window and an /admin console to manage it. Development runs zero-env on PGlite with a dev outbox, so the whole stack boots without external services. An adversarial review caught and closed a server-side bypass of the suspend lock.",
    "outcome": "Built and verified. All 14 of 14 lead-vault tests pass, and the tsc, lint, and build checks come back green. Capture keeps working even when billing lapses: suspended accounts still bank every lead, gated behind a pay-to-access vault. The suspend lock was hardened after an adversarial review closed a server-side bypass.",
    "highlights": [
      "Embed widget or headless endpoint with 5 vertical templates",
      "Delivery only confirms once an alert actually succeeds, so no silent drops",
      "Sheets, Brevo, HubSpot, and webhook sinks with AES-256 encrypted secrets",
      "Speed-to-lead inbox; nurture sequences auto-stop on a human reply",
      "Setup agent auto-extracts business info from the company website",
      "Billing suspend locks the dashboard but never stops capture; leads vault, 7-day grace"
    ],
    "metrics": [
      {
        "value": "14/14",
        "label": "lead-vault tests pass"
      },
      {
        "value": "5",
        "label": "vertical templates"
      },
      {
        "value": "AES-256",
        "label": "encrypted secrets"
      },
      {
        "value": "7-day",
        "label": "billing grace window"
      }
    ],
    "result": "14/14 lead-vault tests pass; capture keeps working even if billing lapses",
    "techStack": [
      "Next.js",
      "TypeScript",
      "PGlite",
      "Drizzle ORM",
      "Tailwind",
      "Resend"
    ],
    "status": "Built",
    "url": null,
    "tier": "standard"
  },
  {
    "slug": "reachnet",
    "name": "ReachNet",
    "category": "SaaS Product",
    "tagline": "Honest-by-design outbound cold email",
    "description": "An outbound cold-email platform built for small businesses. Import prospects from CSV, run multi-step sequences from your own domain, and work replies in a pipeline inbox. Dispatching is idempotent, daily send caps keep volume in check, every send is CAN-SPAM compliant, and one-click unsubscribe ships on every message.",
    "problem": "Small businesses that want to run cold outreach usually get stuck between two bad options. They can blast from a shared sending service that risks their domain reputation and skirts compliance, or they can stitch together spreadsheets and manual follow-ups that drop leads and double-send. Neither one leaves them a clean record of who was contacted, who replied, and who asked to stop.",
    "approach": "ReachNet is the outbound sibling to LeadNet, and it runs on the same Next.js 16 / React 19 / TypeScript stack with Drizzle ORM over Postgres. At the core is an idempotent dispatcher. Every send is keyed, so a retry or a re-run can't fire the same email twice. Daily caps and warm-up guidance throttle volume to protect deliverability. Sending is own-domain-only by design. The system is honest by design too: the moment a reply or an unsubscribe lands, the remaining steps in that prospect's sequence stop instead of pushing through the cadence. CSV import runs deduplication and suppression checks on the way in. Sequences carry merge fields and vertical templates. The whole funnel surfaces in a pipeline inbox (queued → sent → replied → won) with an Outbound Advisor for next steps. CAN-SPAM compliance and one-click unsubscribe are wired into every send rather than bolted on after.",
    "outcome": "The full send → reply → unsubscribe loop is verified in the browser. Prospects import and dedupe. Sequences dispatch under caps from the sending domain. Replies and unsubscribes halt the cadence, and the pipeline inbox reflects each state change. The product is built but not yet deployed.",
    "highlights": [
      "CSV import with automatic deduplication and suppression checks",
      "Multi-step sequences with merge fields and vertical templates",
      "Idempotent dispatcher that never double-sends, with daily caps and warm-up guidance",
      "Own-domain-only sending to protect deliverability and sender reputation",
      "Honest-by-design: a reply or unsubscribe stops the remaining sequence steps",
      "Pipeline inbox (queued → sent → replied → won) with an Outbound Advisor"
    ],
    "metrics": [],
    "result": "Full send → reply → unsubscribe loop verified in the browser",
    "techStack": [
      "Next.js 16",
      "React 19",
      "TypeScript",
      "Drizzle ORM",
      "Postgres",
      "Tailwind"
    ],
    "status": "Built",
    "url": null,
    "tier": "standard"
  },
  {
    "slug": "scoutnet",
    "name": "ScoutNet",
    "category": "AI Agent",
    "tagline": "Find local businesses, score them, draft the pitch, send",
    "description": "A lead-discovery and qualification agent for web professionals. It searches the web for stable local businesses, then reads each site and online presence to score them on two things: income stability and fixable digital gaps. From there it drafts a personalized cold email for every match, auto-sends the strongest ones, and queues the rest for review.",
    "problem": "Freelancers and small web shops lose hours hunting for clients who can actually pay and genuinely need the work, then guessing at a pitch. Most leads are either broke or already have a solid site. Generic cold emails get ignored.",
    "approach": "Forked from the ReachNet outbound infrastructure and built on Next.js 16, React 19, and TypeScript with Drizzle ORM. Discovery pulls candidates from Google Places, OpenStreetMap, or a sample dataset. A deterministic enrichment pass then inspects each business's site for concrete signals, such as SSL, mobile-readiness, stale copy, working forms, and social links, rather than leaning on a black-box model. Every lead gets scored on two transparent axes, income stability and digital gap, and a hybrid send rule decides what happens next. Scores of 80 or higher auto-fire a personalized cold email from the user's own domain via Resend. Anything below that is queued for manual review. Daily send caps, CAN-SPAM compliance, and an unsubscribe-to-suppression path are wired into the send layer, so the agent can run without crossing compliance lines.",
    "outcome": "The full discover, score, pitch, and send pipeline runs end-to-end with compliance built in, and the complete loop was verified in the browser. Built, not yet deployed.",
    "highlights": [
      "Discovers leads from Google Places, OpenStreetMap, or sample data",
      "Scores on two transparent axes: income stability and digital gap",
      "Deterministic site enrichment checks SSL, mobile-readiness, stale copy, forms, socials",
      "Hybrid send: auto-fires scores 80+, queues the rest for review, caps enforced",
      "Sends from the user's own domain via Resend",
      "CAN-SPAM compliant with unsubscribe-to-suppression built in"
    ],
    "metrics": [
      {
        "value": "80+",
        "label": "score to auto-send"
      },
      {
        "value": "2",
        "label": "scoring axes"
      }
    ],
    "result": "Discover → score → pitch → send pipeline runs end-to-end, compliance built in",
    "techStack": [
      "Next.js 16",
      "React 19",
      "TypeScript",
      "Drizzle ORM",
      "Resend"
    ],
    "status": "Built",
    "url": null,
    "tier": "standard"
  },
  {
    "slug": "jarvis",
    "name": "Jarvis",
    "category": "AI Agent",
    "tagline": "An Iron Man–style assistant that builds holograms",
    "description": "A voice-driven personal AI assistant with a holographic fabrication engine. It sees through a camera with Gemini vision and runs on an always-on wake word. Hand it a reference image and it turns that into a 3D hologram, then designs and renders its own builds. Each result gets compared against the reference, with fixes hot-swapped in a self-correction loop.",
    "problem": "Voice assistants stop at conversation. They can't see what's in front of them. They can't build anything you can inspect, and they have no way to check whether their own output is actually correct.",
    "approach": "A FastAPI backend ties three layers together. The input layer stays always-on: a wake word opens a voice channel, and a camera feed goes to Gemini vision so the assistant can reason about what it sees. The graphics layer renders in the browser on Three.js/WebGL. Its Hologram Deconstructor takes a reference image and uses Depth Anything V2 in-browser to lift it into a depth-mapped 3D hologram, which is the Relief engine. The key build is the Fabrication Engine. Rather than treating schematics as flat pictures, it generates them as JARVIS-designed 3D builds described in a rich geometry language, assembling roughly 12 to 30 parts per component. What makes it more than a renderer is the Iron Man self-correction loop. The engine renders its own build, sends that render back through Gemini vision to compare against the reference, then hot-swaps fixes and re-renders. A REFINE control triggers another pass on demand.",
    "outcome": "Built and working. The assistant sees through a camera, deconstructs a reference image into a 3D hologram, then designs and renders its own multi-part 3D build. From there it critiques and corrects that build against the reference in a closing loop. The self-correction loop renders, critiques, and refines its own 3D builds.",
    "highlights": [
      "Always-on wake word and voice, FastAPI backend with Gemini vision",
      "Hologram Deconstructor plus Relief engine using Depth Anything V2, in-browser",
      "Fabrication Engine builds schematics as 3D geometry, 12-30 parts per component",
      "Iron Man self-correction loop: render the build, vision-critique against the reference, refine",
      "REFINE control re-runs the render-compare-fix pass on demand",
      "Browser graphics on Three.js/WebGL, no server round-trip for rendering"
    ],
    "metrics": [
      {
        "value": "12-30",
        "label": "parts per component"
      }
    ],
    "result": "Self-correction loop renders, critiques, and refines its own 3D builds",
    "techStack": [
      "Python",
      "FastAPI",
      "Gemini",
      "Three.js",
      "Depth Anything V2",
      "WebGL"
    ],
    "status": "Built",
    "url": null,
    "tier": "flagship"
  },
  {
    "slug": "intern-agent",
    "name": "Intern Agent",
    "category": "AI Agent",
    "tagline": "An autonomous AI internship hunter",
    "description": "An autonomous agent that runs internship hunting from start to finish. It scrapes 8+ job boards, scores each opening against your résumé, writes personalised cover letters, and manages the whole application pipeline with tracking and analytics.",
    "problem": "Internship hunting is a high-volume grind. The same listings show up across LinkedIn, Indeed, Glassdoor, Handshake, and WayUp, and every one wants a tailored cover letter, a manual apply, and a follow-up you forget to send. Do it by hand and you either apply to a handful of roles well or to a lot of roles badly.",
    "approach": "The agent is a staged Python pipeline: scrape, score, apply, follow-up. Each opening moves through as a tracked record in SQLite. Scrapers pull from 8+ boards (LinkedIn, Indeed, Glassdoor, Handshake, WayUp), then a match-scoring step ranks every role against the résumé using demand analysis and skills-gap detection, so the highest-fit listings float to the top. The Claude API writes a personalised cover letter per role with A/B/C tone variants, and Playwright drives the actual submission. Both sit behind an outbox and approvals, so nothing goes out unreviewed. A Streamlit interface ties the loop together with pipeline tracking and analytics, and follow-ups get scheduled off the same record.",
    "outcome": "Built and shipping at 3,200+ lines. It's a complete scrape → score → apply → follow-up pipeline with an outbox, an approval gate, Playwright auto-apply, and follow-up scheduling, all surfaced through a Streamlit dashboard with tracking and analytics.",
    "highlights": [
      "Scrapes 8+ boards: LinkedIn, Indeed, Glassdoor, Handshake, WayUp",
      "Match scoring against your résumé using demand analysis and skills-gap detection",
      "AI cover-letter generation with A/B/C tone variants via the Claude API",
      "Playwright auto-apply behind an outbox and approval gate",
      "One Streamlit dashboard for tracking, analytics, and scheduled follow-ups",
      "SQLite-backed records carry each opening from scrape through follow-up"
    ],
    "metrics": [
      {
        "value": "3,200+",
        "label": "lines shipped"
      },
      {
        "value": "8+",
        "label": "job boards scraped"
      },
      {
        "value": "A/B/C",
        "label": "cover-letter tone variants"
      }
    ],
    "result": "3,200+ lines shipping a full scrape → score → apply → follow-up pipeline",
    "techStack": [
      "Python",
      "Streamlit",
      "SQLite",
      "Playwright",
      "Claude API"
    ],
    "status": "Built",
    "url": null,
    "tier": "standard"
  },
  {
    "slug": "mission-control",
    "name": "Mission Control",
    "category": "Developer Tool",
    "tagline": "A local command center for your whole project fleet",
    "description": "A local macOS command center that watches an entire project fleet from one pane of glass. Live status lights, KPI sparklines, git freshness, uptime, and launchd schedule checks all stream in from a 24/7 Node daemon, rendered behind a NASA-ops interface.",
    "problem": "Run a dozen projects at once and their health scatters across terminals, cron logs, and git checkouts. You find out something broke long after it actually did. There's no single place to glance at and know which projects are fresh, running, and on schedule.",
    "approach": "A 24/7 Node daemon runs real probes against each project: git freshness, uptime, launchd schedule state, KPIs. It writes the results to a node:sqlite telemetry store. The Next.js 15 / React 19 front end, written in TypeScript, renders them as a read-only Fleet Grid and pushes updates over SSE every 30 seconds. Boot starts with an env safety gate, a self-test that fails closed if it detects a secret leak before the daemon comes up. On top of that sits the M3 hole-finder. It runs suggest-only audit agents that spawn the trusted Claude CLI in read-only mode and hand back findings instead of touching code.",
    "outcome": "Built and running locally. It monitors 12 projects in one Fleet Grid with live status lights and KPI sparklines. The audit agents have already surfaced 5 real findings, proven on the troy project, with no write access to any monitored repo.",
    "highlights": [
      "Read-only Fleet Grid with live status lights and KPI sparklines",
      "Git freshness, uptime, and launchd schedule probes every 30s",
      "24/7 Node daemon writes telemetry to a node:sqlite store, streamed over SSE",
      "Env safety gate: boot self-test fails closed on secret leaks",
      "Suggest-only audit agents spawn a read-only Claude CLI and return findings",
      "Monitors 12 projects; audit agents surfaced 5 real findings on troy"
    ],
    "metrics": [
      {
        "value": "12",
        "label": "projects monitored"
      },
      {
        "value": "5",
        "label": "real findings surfaced"
      },
      {
        "value": "30s",
        "label": "probe interval"
      },
      {
        "value": "24/7",
        "label": "telemetry daemon"
      }
    ],
    "result": "Running locally — monitors 12 projects; audit agents surfaced 5 real findings",
    "techStack": [
      "Next.js 15",
      "React 19",
      "Node.js",
      "node:sqlite",
      "SSE",
      "TypeScript"
    ],
    "status": "Built",
    "url": null,
    "tier": "standard"
  },
  {
    "slug": "stock-trader",
    "name": "Stock Trader V7",
    "category": "Quant / Trading",
    "tagline": "Sector rotation that trades itself — and the honest numbers behind it",
    "description": "A systematic equity engine running leveraged sector rotation off momentum and volatility targeting. The V7 \"PUSH-20\" strategy has traded hands-off on an Alpaca paper account since June 9, 2026. Its headline backtest was re-run under an independent validation harness, then put through a formal overfitting audit in August 2026 — both passes corrected the story, and the corrected version is the one published here.",
    "problem": "Discretionary trading is inconsistent and eats your time. Most \"systems\" never actually run unattended — they live in a backtest notebook and die there. And most published backtests quietly flatter themselves through optimistic cost assumptions and through the dozens of variations that were tried and never mentioned, which is how a strategy looks great on paper and disappoints in practice.",
    "approach": "The engine ranks sectors by momentum, sizes positions with volatility targeting, then applies leverage. Execution runs as a two-speed loop: a 60-second cycle checks open positions and order fills, while a separate daily cycle recomputes signals and rotates the book. The more interesting work was the two rounds of self-criticism. The first re-ran the strategy at a realistic 10 basis points of slippage instead of the original 5, then attacked it with walk-forward testing, a timing-luck study across six different start months, and a parameter sweep. The second, in August 2026, applied a Deflated Sharpe Ratio and a Probability of Backtest Overfitting analysis — the standard tests for whether a result is simply the best of many things that were tried.",
    "outcome": "The validation corrected the headline down: real performance is 19.0% CAGR against a −36.6% max drawdown, not the 20.7% / −30% originally published. The August overfitting audit then split the result in two. The direction is real — a Deflated Sharpe Ratio of 0.9991 says the edge is very unlikely to be an artefact of having tried many variations. The precision is not: many different risk-dial settings fit the history about equally well, so the specific tuned values are not identifiable from the data and should not be treated as optimal. Two independent simulators also disagree on trading-cost assumptions, which is logged as open rather than resolved quietly.",
    "highlights": [
      "19.0% CAGR / −36.6% max drawdown, validated at realistic 10 bps slippage",
      "Deflated Sharpe Ratio of 0.9991 — the edge survives correction for how many variants were tried",
      "The risk-dial tuning is NOT identifiable from the data, and the write-up says so plainly",
      "Original 20.7% / −30% headline found optimistic and publicly corrected",
      "Beat the benchmark in 5 of 5 walk-forward sub-periods, with a 0.8pp spread across six start months",
      "Known weakness documented: loses ~1.6× the benchmark in fast whipsaw selloffs",
      "Trades hands-off on Alpaca paper on a scheduled loop, with slippage tracking"
    ],
    "metrics": [
      {
        "value": "19.0%",
        "label": "CAGR (validated, 10 bps)"
      },
      {
        "value": "−36.6%",
        "label": "max drawdown (validated)"
      },
      {
        "value": "0.9991",
        "label": "deflated Sharpe — the edge survives"
      },
      {
        "value": "5/5",
        "label": "walk-forward periods beating SPY"
      }
    ],
    "result": "The direction is real, the fine-tuning is not — and the audit that found that is published too",
    "techStack": [
      "Python",
      "pandas",
      "numpy",
      "yfinance",
      "Alpaca API",
      "pytest"
    ],
    "status": "Live",
    "url": null,
    "tier": "flagship"
  },
  {
    "slug": "futures-trader",
    "name": "NQ Futures Quant Suite",
    "category": "Quant / Trading",
    "tagline": "Proving what a Nasdaq-only system can't do, then shipping what it can",
    "description": "A 30-year research programme on systematically trading the Nasdaq-100. The brief asked for 30%+ annual returns from a single instrument. The interesting result is the proof that it doesn't exist — and the strategy that does, published with its costs, its caveats and its failure modes attached.",
    "problem": "The brief was 30%+ CAGR trading the Nasdaq alone, with drawdowns kept small. Most backtests answering a brief like that quietly flatter themselves: they ignore financing on borrowed money, assume free execution, peek at data they wouldn't have had, or tune parameters until one lucky configuration looks brilliant. The real question was not how good a number I could produce, but which numbers survive honest accounting.",
    "approach": "The strategy counts how many of the 63, 126 and 252-day returns are positive and maps that vote to a target exposure, gates leverage on the 200-day moving average, scales position size to hit a 30% volatility target, halves the leverage cap whenever equity sits more than 10% below its high-water mark, and only trades when leverage drifts far enough to be worth the cost. Every signal is lagged a full day. Financing is charged at the T-bill rate on borrowed notional and idle margin earns T-bills, so leverage costs what leverage actually costs. The configuration was then split in and out of sample, walked forward, and pushed through a Monte Carlo to find how often the drawdown budget breaks.",
    "outcome": "The shipped configuration returns 16.1% annually against a 32.9% maximum drawdown over 30 years, with the out-of-sample period scoring better than the in-sample — the opposite of an overfitting signature. Buy-and-hold over the same window returns 13.2% but with an 82.9% drawdown, so the edge is risk containment rather than raw return. Two harder claims were proven false: 30%+ CAGR on this instrument is unreachable at the available Sharpe without ruinous volatility, and 25% CAGR inside a 20% drawdown budget is impossible — the honest frontier maximum is 12.2%. The strategy is also ported to TradingView Pine Script and published open-source alongside the research.",
    "highlights": [
      "16.1% CAGR / −32.9% max drawdown over 30 years, financing and costs modelled",
      "Out-of-sample Sharpe 0.75 beats in-sample 0.66 — no overfitting signature",
      "Proved 30%+ CAGR on a single index is unreachable, rather than claiming it",
      "Proved 25% CAGR under a −20% drawdown budget impossible; real frontier max is 12.2%",
      "Rejected after testing: shorting, leverage caps above 5x, indicator stacks, fixed R:R stops",
      "Ported to TradingView Pine Script, with every deviation from the Python documented"
    ],
    "metrics": [
      {
        "value": "16.1%",
        "label": "CAGR, 30yr, costs modelled"
      },
      {
        "value": "−32.9%",
        "label": "max drawdown"
      },
      {
        "value": "0.75",
        "label": "out-of-sample Sharpe (> in-sample)"
      },
      {
        "value": "30 yrs",
        "label": "backtest span, 1996–2026"
      }
    ],
    "result": "16.1% CAGR over 30 years — and a proof the 30% brief was impossible",
    "techStack": [
      "Python",
      "NumPy",
      "Pandas",
      "Pine Script"
    ],
    "status": "Backtest only",
    "url": "https://github.com/nyaungnicholas-wq/futures-trader",
    "tier": "flagship"
  },
  {
    "slug": "signaldeck",
    "name": "SignalDeck",
    "category": "Quant / Trading",
    "tagline": "A market-research platform built to catch itself being wrong",
    "description": "A market-measurement and research-record platform built around measurement discipline rather than prediction. It records live data, computes scores, and grades its own predictions against a protocol fixed before the outcomes were known, retiring what fails. It is not an auto-trader, has no broker connection, and executes nothing.",
    "problem": "Most trading systems report the accuracy they want to report: pooled observations that inflate the sample, a null that flatters any signal in a trending market, and a claimed edge that nothing independent ever re-checks. A number no process can falsify is decoration, not evidence.",
    "approach": "Every prediction writes a hash-chained ledger row with its probability frozen at prediction time. Grading uses one observation per symbol, horizon, and UTC day against a walk-forward majority-class null. Claims are pre-registered with resolution rules and nulls frozen into the chain before the first observation could resolve. The system enforces multiple-testing corrections, survivorship and point-in-time data repairs (with quantified residuals for 2023-2025), a documentation gate in CI that blocks claim drift, a self-grading user-experience rubric, and a simplified reading mode for non-specialists. The directional ensemble was auto-retired by a pre-registered rule when its live interval fell below the baseline.",
    "outcome": "The platform has demonstrated a working measurement and retirement process, but not predictive skill on live data. The directional family was graded at 43.1% on 2,911 graded observations against a 56.8% baseline and auto-retired. The structural predictors (trend21, vol21, liquidity21) are pending, with first grading under the pre-registered protocol not until 2026-08-14. The project holds no live capital and executes no trades.",
    "highlights": [
      "Hash-chained prediction ledger — every probability is frozen and tamper-evident at the moment it is recorded",
      "Directional ensemble graded at 43.1% vs a 56.8% null and auto-retired by a pre-registered rule",
      "Multiple-testing controls and pre-registered claims to stop the system fooling itself",
      "Survivorship and point-in-time data repairs with quantified residuals, documented in CI",
      "Self-grading rubric and simplified reading mode for non-specialists",
      "Bias controls that are built and in force, including drift monitoring, canary rollout, and data-quality checks"
    ],
    "metrics": [
      {
        "value": "-13.7pp",
        "label": "measured skill — so the signal was retired"
      },
      {
        "value": "1,854,228",
        "label": "rows in the survivorship-aware universe"
      },
      {
        "value": "3,649",
        "label": "forecasts recorded, awaiting their grading date"
      }
    ],
    "result": "The platform's only defensible claim is procedural, not predictive: it grades its own predictions and retires what fails",
    "techStack": [
      "Go",
      "SQLite",
      "Next.js",
      "Python",
      "Walk-forward validation"
    ],
    "status": "Built",
    "url": null,
    "tier": "flagship",
    "custom": true
  },
  {
    "slug": "shanty-realestate",
    "name": "Shanty Soerjono — Realtor Site",
    "category": "Website",
    "tagline": "A live probate-realtor platform, and the print book that goes with it",
    "description": "A Next.js marketing site for a probate and trust specialist realtor serving LA County and Orange County. The homepage leans hard into motion: parallax, a 3D house model, constellation effects. Behind it runs an inbound funnel that turns visitors into leads through forms, gated content, and an AI probate assistant. Live in production, and the engagement has since extended into print — a 16-page probate guide built from the same approved copy.",
    "problem": "A probate and trust specialist realtor needed real inbound leads in a niche most agents ignore. A brochure site wouldn't cut it. Probate sellers show up mid-process with specific questions, so the site had to answer those questions and route the lead into follow-up instead of just listing a phone number. The print guide had the opposite constraint: it goes to people dealing with a death in the family and a court process, so not a word of the approved copy could drift.",
    "approach": "Built on Next.js 16 and React 19. The homepage motion layers Framer Motion parallax, a Three.js 3D home, and constellation effects. The AI probate assistant runs on Gemini with an automatic NIM fallback, so a model outage degrades to a backup provider rather than a dead chat. Lead capture is decoupled from any single CRM. A form submission fans out to env-gated Resend, HubSpot, Brevo, and Sheets sinks, so each destination toggles on with its own credentials and missing keys skip that sink instead of breaking the form. The print guide is built the same way software is: the approved copy lives in one plain-text file, the layout is generated from it, and a checker compares every line of that file against the rendered pages — a single missing or reworded line fails the build.",
    "outcome": "Shipped and live in production at shanty-realestate.com since June 2026, with the probate assistant, the multi-sink lead funnel, and three intent-based nurture sequences all running on a real business domain. The 16-page \"Understanding Probate\" guide followed in August 2026 — print-ready at 8×11 portrait, paginated as a multiple of four so it saddle-stitches into a booklet with no blank leaves.",
    "highlights": [
      "AI probate assistant on Gemini with an automatic NIM fallback",
      "Lead capture fans out to env-gated Resend, HubSpot, Brevo & Sheets sinks",
      "Framer Motion parallax, a Three.js 3D home, and constellation effects",
      "Automated nurture sequences split into probate, buyer, and attorney paths",
      "16-page print guide generated from one copy file, with a build-time checker enforcing it verbatim",
      "Live in production on the realtor's real domain since June 2026"
    ],
    "metrics": [
      {
        "value": "16",
        "label": "print pages, saddle-stitch ready"
      },
      {
        "value": "4",
        "label": "lead sinks, each independently toggled"
      },
      {
        "value": "3",
        "label": "nurture paths by visitor intent"
      }
    ],
    "result": "Live at shanty-realestate.com since Jun 2026 — and the same client came back for print",
    "techStack": [
      "Next.js 16",
      "React 19",
      "Framer Motion",
      "Three.js",
      "Tailwind",
      "Gemini"
    ],
    "status": "Live",
    "url": "https://shanty-realestate.com",
    "tier": "flagship"
  },
  {
    "slug": "troy-njrotc-site",
    "name": "Troy NJROTC Warriors",
    "category": "Website",
    "tagline": "A cinematic, naval-inspired redesign for a JROTC unit",
    "description": "A static redesign of troynjrotc.org for a high-school Navy JROTC program. The front door is a WebGL hero scene: a fresnel energy core, a wireframe globe, orbiting gyroscope rings, and a parallax starfield, all moving under smooth scroll animation. A dark navy, red, and white design system carries that look across 30+ pages.",
    "problem": "A JROTC unit's site has to carry a large, sprawling program. That means the core unit plus a dozen-plus competitive teams, all while still reading like a naval organization. Most templated school sites manage neither. They flatten everything into the same generic pages and feel nothing like the unit they represent.",
    "approach": "The hero is a Three.js WebGL scene built around a custom fresnel shader. The energy core glows brighter at its edges, where the view angle grazes the surface, and it's wrapped by a wireframe globe, orbiting gyroscope rings, and a parallax particle starfield for depth. Motion runs on Lenis for smooth scroll, feeding GSAP ScrollTrigger so animations fire as sections enter the viewport instead of on a timer. The whole thing is static JavaScript with no build step or backend. That lets the 30+ pages, including 12+ dedicated competitive-team pages for CyberPatriot, robotics, and StellarXplorers, share one navy/red/white design system in Cinzel and Oswald rather than getting squeezed into a single template.",
    "outcome": "Built and ready to ship: 30+ pages with the custom WebGL hero and per-team sections. Not yet deployed.",
    "highlights": [
      "Three.js WebGL hero with a custom fresnel core, wireframe globe, orbit rings, and starfield",
      "GSAP ScrollTrigger driven by Lenis for scroll-triggered animation",
      "12+ dedicated competitive-team pages (CyberPatriot, robotics, StellarXplorers)",
      "Navy / red / white design system in Cinzel and Oswald typography",
      "Fully static JavaScript, with no build step and no backend",
      "30+ pages sharing one consistent naval design language"
    ],
    "metrics": [
      {
        "value": "30+",
        "label": "pages"
      },
      {
        "value": "12+",
        "label": "competitive-team pages"
      }
    ],
    "result": "30+ pages with a custom WebGL hero, built and ready to ship",
    "techStack": [
      "Three.js",
      "GSAP",
      "ScrollTrigger",
      "Lenis",
      "WebGL",
      "JavaScript"
    ],
    "status": "Built",
    "url": null,
    "tier": "standard"
  },
  {
    "slug": "mintset",
    "name": "MINTSET",
    "category": "Content Engine",
    "tagline": "A weekly autopilot factory for finance reels",
    "description": "A fully autonomous content engine for finance storytelling reels. AI writes the scripts, a deterministic Remotion factory renders them, and scheduled crons post to @mint._.set with no human in the loop. It was built for a creator who needs to publish daily short-form without doing the daily work.",
    "problem": "Posting short-form video consistently is a grind, and it burns creators out within weeks. The daily scripting, voiceover, editing, captioning, and publishing never stop. MINTSET takes the human out of that loop so the cadence holds without anyone showing up every day.",
    "approach": "The core is a deterministic \"V7 factory.\" Each reel is defined by a JSON spec, and the same locked Remotion template renders it into a unique reel: ElevenLabs voiceover, 8 FLUX-generated images, beat-synced caption phrases, and generated code. Output stays repeatable but never comes out identical. Two launchd crons run the whole machine. A Sunday 5pm job kicks off a multi-agent batch that writes the next week's 7 scripts and renders all 7 up front. Then a daily 5pm cron posts one pre-rendered reel through the Buffer API with no approval gate. A ManyChat funnel sits downstream of the posts to capture interest.",
    "outcome": "Live and running hands-off. Every Sunday it writes and renders the week's seven reels. Every day a cron publishes one to @mint._.set as 1 TikTok plus 5 Instagram parts. Script to publish, with no human in the loop.",
    "highlights": [
      "Weekly multi-agent batch writes 7 human-scorable scripts every Sunday",
      "Deterministic V7 factory: one locked template, unique VO, music, and imagery per reel",
      "JSON-spec pipeline running ElevenLabs TTS, 8 FLUX images, beat-synced captions, and generated code",
      "Two launchd crons: Sunday renders all 7, daily posts one with no approval gate",
      "Publishes to @mint._.set as 1 TikTok plus 5 Instagram parts daily",
      "ManyChat funnel downstream of posts to capture interest"
    ],
    "metrics": [
      {
        "value": "7",
        "label": "scripts written & rendered weekly"
      },
      {
        "value": "8",
        "label": "FLUX images per reel"
      },
      {
        "value": "1 + 5",
        "label": "TikTok + IG parts posted daily"
      }
    ],
    "result": "Live & autonomous — 1 TikTok + 5 Instagram parts posted daily, hands-off",
    "techStack": [
      "Remotion",
      "React",
      "Node.js",
      "ElevenLabs",
      "FLUX",
      "Buffer API"
    ],
    "status": "Live",
    "url": null,
    "tier": "flagship"
  },
  {
    "slug": "finance-book",
    "name": "Money, Finally Explained",
    "category": "Content Engine",
    "tagline": "Personal finance from zero, for 16–24 year-olds",
    "description": "A 150-page personal-finance book for 16–24 year-olds that teaches money from a first paycheck all the way to retirement. It reads at an 8th-grade level and never drops jargon without explaining it. Roth IRA and 401(k) get full step-by-step walkthroughs, and three recurring characters keep the lessons grounded in real situations.",
    "problem": "Most beginner finance content assumes you already get jargon, charts, and tax brackets. So the people who need the basics most, teens and young adults staring down a first paycheck, lose the thread early and quit. This book starts from zero and stays readable the whole way through.",
    "approach": "I wrote the manuscript in Markdown at an 8th-grade reading level, then built clean EPUB3 and PDF editions from that one source. The charts (tax brackets, compounding, market history) are generated with Matplotlib, so the visuals match the text and rebuild straight from the data. A Python toolchain holds the manuscript, charts, and outputs together. Three recurring characters and documented real stories, Ronald Read, Buffett, the 2008 crash, give the financial concepts a narrative spine rather than a pile of isolated definitions.",
    "outcome": "Complete and built. 26 chapters and 99k+ words, with EPUB and PDF production builds ready to go. The full manuscript, the charts, and both editions are finished and generated from a single source.",
    "highlights": [
      "26 chapters, 99k+ words, fully written and built",
      "EPUB + PDF production builds ready from a single source",
      "Teaches how to read charts, tax brackets and compounding visually",
      "Step-by-step Roth IRA and 401(k) walkthroughs from zero",
      "Three recurring characters anchor concepts in real situations",
      "Real documented stories: Ronald Read, Buffett, the 2008 crash"
    ],
    "metrics": [
      {
        "value": "26",
        "label": "chapters"
      },
      {
        "value": "99k+",
        "label": "words written"
      },
      {
        "value": "150",
        "label": "pages"
      },
      {
        "value": "2",
        "label": "editions (EPUB / PDF)"
      }
    ],
    "result": "Complete — 26 chapters / 99k+ words, EPUB + PDF builds ready",
    "techStack": [
      "Python",
      "Markdown",
      "EPUB3",
      "PDF",
      "Matplotlib charts"
    ],
    "status": "Built",
    "url": null,
    "tier": "standard"
  },
  {
    "slug": "fintwit-dashboard",
    "name": "Investor Alpha Hub",
    "category": "SaaS Product",
    "tagline": "Track institutional money moves in real time",
    "description": "A financial-intelligence dashboard that puts institutional money moves in front of retail investors. Hedge funds, politicians, insiders, and sovereign wealth funds, all in one place. You get real-time catalysts and multi-source sentiment, plus a multi-gate safety framework that cross-checks signals before you act on them.",
    "problem": "Retail investors who want to follow \\\"smart money\\\" end up stitching together scattered 13F filings, congressional disclosures, insider forms, and sovereign-fund reports by hand. Any single source can run late, get noisy, or be flat-out wrong. Nothing consolidates the view, shows you who's moving, and forces you to verify a signal before you trade on it.",
    "approach": "The dashboard pulls activity from 9 market data sources into one feed. It covers 28+ tracked investors sorted into 7 categories: hedge funds, politicians, insiders, sovereign wealth funds, and more. Two checks sit on top of that feed. Multi-source sentiment keeps any single feed from driving the read, and a multi-gate safety validation framework cross-verifies a signal across gates before it ever surfaces as actionable. The front end is static, built in vanilla JS, HTML5, and CSS3 with no framework. The OLED dark-mode interface uses Fira Sans for the UI and Fira Code for tabular figures, held at 4.5:1 contrast so dense rows of numbers stay legible at a glance.",
    "outcome": "Shipped and Built. The dashboard tracks 28+ investors across 7 categories from 9 live data sources. Real-time catalysts run alongside multi-source sentiment and the multi-gate safety checks, all in a single OLED dark interface.",
    "highlights": [
      "Tracks 28+ investors across 7 categories in one feed",
      "Real-time catalysts pulled from 9 market data sources",
      "Multi-source sentiment so no single feed drives the read",
      "Multi-gate safety validation cross-checks signals before action",
      "OLED dark UI, Fira Code tabular figures, 4.5:1 contrast",
      "Static vanilla-JS front end, no framework dependencies"
    ],
    "metrics": [
      {
        "value": "28+",
        "label": "investors tracked"
      },
      {
        "value": "7",
        "label": "investor categories"
      },
      {
        "value": "9",
        "label": "live data sources"
      },
      {
        "value": "4.5:1",
        "label": "UI contrast ratio"
      }
    ],
    "result": "Tracks 28+ investors across 7 categories from 9 live data sources",
    "techStack": [
      "HTML5",
      "CSS3",
      "Vanilla JS",
      "Fira Sans",
      "Fira Code"
    ],
    "status": "Built",
    "url": null,
    "tier": "standard"
  }
];


/* ============================================================
   TESTIMONIALS — fill these in with REAL client quotes to make
   the "What clients say" section appear (hidden while empty).
   Example shape:
   { quote: "Nicholas shipped our MVP in 5 weeks, solo.", name: "Shanty Soerjono",
     title: "Probate & Trust Realtor", url: "https://shanty-realestate.com" }
   ============================================================ */
window.NS_TESTIMONIALS = [
  // { quote: "", name: "", title: "", url: "" },
];
