/* ============================================================
   NICHOLAS — portfolio data
   Curated to the studio's OWN builds. External clones
   (graphify, ArcReel) deliberately excluded. Jarvis is
   represented as the custom Iron Man assistant only.
   Each project carries a truthful result + a full case write-up
   (problem / approach / outcome / highlights / metrics).
   Generated by build-data.mjs — edit .enriched.json or FIXED there.
   ============================================================ */
window.NS_PROJECTS = [
  {
    "slug": "grownet",
    "name": "GrowNet",
    "category": "SaaS Product",
    "tagline": "One funnel that catches leads and starts conversations",
    "description": "GrowNet is one growth platform that runs inbound lead capture and outbound cold outreach side by side for small teams. It sits on a spine-first data model: one person is exactly one record, so the two channels can never work the same contact at once.",
    "problem": "Teams that run inbound and outbound on separate tools waste leads. The same person gets cold-emailed while a nurture sequence is already running. No system owns the contact, so the channels step on each other and the prospect ends up with a confusing double-touch.",
    "approach": "GrowNet came from merging two earlier products, LeadNet (inbound) and ReachNet (outbound), into one contact-spine data model where each person is a single record both channels read and write. The interference problem gets solved in the database rather than the UI. A single-active-automation lock means a contact can have at most one running automation, so a nurture sequence and a cold campaign can never fire on the same person at the same time. An import warm-exclusion guard catches the correlation case right at ingestion: newly imported prospects are held back from outbound if they already exist as warm inbound contacts. On top of the unified funnel sits a Growth Advisor that reads the whole pipeline and surfaces correlation-aware next moves. An onboarding agent reads a company website to pre-write copy and set up sender identity. The design was worked out council-first before any building started. Stack: Next.js, React 19, TypeScript, Drizzle ORM, Postgres, Tailwind, with an indigo/emerald/sky three-channel UI.",
    "outcome": "Built and verified. The full inbound to outbound loop was run twice as the client, both passes green, and the next build passed. Status is Built, not yet deployed.",
    "highlights": [
      "Merges LeadNet inbound and ReachNet outbound into one contact-spine data model",
      "Single-active-automation lock, enforced in the database, blocks channel collisions",
      "Import warm-exclusion guard holds back prospects who are already warm inbound contacts",
      "Inbound capture forms and an outbound campaign dispatcher live in one interface",
      "Growth Advisor reads the whole funnel and surfaces correlation-aware next moves",
      "Onboarding agent reads a website to pre-write copy and set up sender identity"
    ],
    "metrics": [
      {
        "value": "1",
        "label": "record per person (contact spine)"
      },
      {
        "value": "2",
        "label": "channels, one lock"
      },
      {
        "value": "2x",
        "label": "full-loop client passes, both green"
      }
    ],
    "result": "Full inbound → outbound loop verified twice as a client — both passes green",
    "techStack": [
      "Next.js",
      "React 19",
      "TypeScript",
      "Drizzle ORM",
      "Postgres",
      "Tailwind"
    ],
    "status": "Built",
    "url": null,
    "tier": "flagship"
  },
  {
    "slug": "leadnet",
    "name": "LeadNet",
    "category": "SaaS Product",
    "tagline": "Speed-to-lead capture for local small businesses",
    "description": "A multi-tenant lead-capture SaaS for local small businesses. It catches every form submission, fires instant alerts and branded auto-replies, then nurtures leads through multi-step email sequences. It's built for realtors, contractors, and attorneys who win by answering fast. Delivery is only confirmed once an alert actually succeeds.",
    "problem": "Local businesses lose deals when they answer leads too slowly. Most capture tools make it worse: they quietly drop submissions when an alert fails or when billing lapses. The lead that came in while you were on a job site is usually the one you needed most. And a tool that stops capturing the moment a card expires turns a billing hiccup into lost revenue.",
    "approach": "Leads arrive through an embeddable widget or a headless endpoint. On every submission the system fans out to configured sinks (Google Sheets, Brevo, HubSpot, or a webhook), with secrets held under AES-256 encryption. It only confirms delivery to the submitter once an alert has actually succeeded, so a silent failure can't masquerade as a saved lead. Five vertical templates pre-shape forms and copy per industry, and a setup agent reads the company website to auto-extract business info during onboarding. The nurture engine drives multi-step email sequences that auto-stop the moment a human reply lands. On top of the speed-to-lead inbox sit the reply engine and inbound advisor. The defining design decision is that capture is always-on while billing is decoupled from it. An operator can manually suspend an account, which locks the dashboard but never stops capture. Leads keep flowing into a vault that the customer pays to access, with a 7-day grace window and an /admin console to manage it. Development runs zero-env on PGlite with a dev outbox, so the whole stack boots without external services. An adversarial review caught and closed a server-side bypass of the suspend lock.",
    "outcome": "Built and verified. All 14 of 14 lead-vault tests pass, and the tsc, lint, and build checks come back green. Capture keeps working even when billing lapses: suspended accounts still bank every lead, gated behind a pay-to-access vault. The suspend lock was hardened after an adversarial review closed a server-side bypass.",
    "highlights": [
      "Embed widget or headless endpoint with 5 vertical templates",
      "Delivery only confirms once an alert actually succeeds, so no silent drops",
      "Sheets, Brevo, HubSpot, and webhook sinks with AES-256 encrypted secrets",
      "Speed-to-lead inbox; nurture sequences auto-stop on a human reply",
      "Setup agent auto-extracts business info from the company website",
      "Billing suspend locks the dashboard but never stops capture; leads vault, 7-day grace"
    ],
    "metrics": [
      {
        "value": "14/14",
        "label": "lead-vault tests pass"
      },
      {
        "value": "5",
        "label": "vertical templates"
      },
      {
        "value": "AES-256",
        "label": "encrypted secrets"
      },
      {
        "value": "7-day",
        "label": "billing grace window"
      }
    ],
    "result": "14/14 lead-vault tests pass; capture keeps working even if billing lapses",
    "techStack": [
      "Next.js",
      "TypeScript",
      "PGlite",
      "Drizzle ORM",
      "Tailwind",
      "Resend"
    ],
    "status": "Built",
    "url": null,
    "tier": "standard"
  },
  {
    "slug": "reachnet",
    "name": "ReachNet",
    "category": "SaaS Product",
    "tagline": "Honest-by-design outbound cold email",
    "description": "An outbound cold-email platform built for small businesses. Import prospects from CSV, run multi-step sequences from your own domain, and work replies in a pipeline inbox. Dispatching is idempotent, daily send caps keep volume in check, every send is CAN-SPAM compliant, and one-click unsubscribe ships on every message.",
    "problem": "Small businesses that want to run cold outreach usually get stuck between two bad options. They can blast from a shared sending service that risks their domain reputation and skirts compliance, or they can stitch together spreadsheets and manual follow-ups that drop leads and double-send. Neither one leaves them a clean record of who was contacted, who replied, and who asked to stop.",
    "approach": "ReachNet is the outbound sibling to LeadNet, and it runs on the same Next.js 16 / React 19 / TypeScript stack with Drizzle ORM over Postgres. At the core is an idempotent dispatcher. Every send is keyed, so a retry or a re-run can't fire the same email twice. Daily caps and warm-up guidance throttle volume to protect deliverability. Sending is own-domain-only by design. The system is honest by design too: the moment a reply or an unsubscribe lands, the remaining steps in that prospect's sequence stop instead of pushing through the cadence. CSV import runs deduplication and suppression checks on the way in. Sequences carry merge fields and vertical templates. The whole funnel surfaces in a pipeline inbox (queued → sent → replied → won) with an Outbound Advisor for next steps. CAN-SPAM compliance and one-click unsubscribe are wired into every send rather than bolted on after.",
    "outcome": "The full send → reply → unsubscribe loop is verified in the browser. Prospects import and dedupe. Sequences dispatch under caps from the sending domain. Replies and unsubscribes halt the cadence, and the pipeline inbox reflects each state change. The product is built but not yet deployed.",
    "highlights": [
      "CSV import with automatic deduplication and suppression checks",
      "Multi-step sequences with merge fields and vertical templates",
      "Idempotent dispatcher that never double-sends, with daily caps and warm-up guidance",
      "Own-domain-only sending to protect deliverability and sender reputation",
      "Honest-by-design: a reply or unsubscribe stops the remaining sequence steps",
      "Pipeline inbox (queued → sent → replied → won) with an Outbound Advisor"
    ],
    "metrics": [],
    "result": "Full send → reply → unsubscribe loop verified in the browser",
    "techStack": [
      "Next.js 16",
      "React 19",
      "TypeScript",
      "Drizzle ORM",
      "Postgres",
      "Tailwind"
    ],
    "status": "Built",
    "url": null,
    "tier": "standard"
  },
  {
    "slug": "scoutnet",
    "name": "ScoutNet",
    "category": "AI Agent",
    "tagline": "Find local businesses, score them, draft the pitch, send",
    "description": "A lead-discovery and qualification agent for web professionals. It searches the web for stable local businesses, then reads each site and online presence to score them on two things: income stability and fixable digital gaps. From there it drafts a personalized cold email for every match, auto-sends the strongest ones, and queues the rest for review.",
    "problem": "Freelancers and small web shops lose hours hunting for clients who can actually pay and genuinely need the work, then guessing at a pitch. Most leads are either broke or already have a solid site. Generic cold emails get ignored.",
    "approach": "Forked from the ReachNet outbound infrastructure and built on Next.js 16, React 19, and TypeScript with Drizzle ORM. Discovery pulls candidates from Google Places, OpenStreetMap, or a sample dataset. A deterministic enrichment pass then inspects each business's site for concrete signals, such as SSL, mobile-readiness, stale copy, working forms, and social links, rather than leaning on a black-box model. Every lead gets scored on two transparent axes, income stability and digital gap, and a hybrid send rule decides what happens next. Scores of 80 or higher auto-fire a personalized cold email from the user's own domain via Resend. Anything below that is queued for manual review. Daily send caps, CAN-SPAM compliance, and an unsubscribe-to-suppression path are wired into the send layer, so the agent can run without crossing compliance lines.",
    "outcome": "The full discover, score, pitch, and send pipeline runs end-to-end with compliance built in, and the complete loop was verified in the browser. Built, not yet deployed.",
    "highlights": [
      "Discovers leads from Google Places, OpenStreetMap, or sample data",
      "Scores on two transparent axes: income stability and digital gap",
      "Deterministic site enrichment checks SSL, mobile-readiness, stale copy, forms, socials",
      "Hybrid send: auto-fires scores 80+, queues the rest for review, caps enforced",
      "Sends from the user's own domain via Resend",
      "CAN-SPAM compliant with unsubscribe-to-suppression built in"
    ],
    "metrics": [
      {
        "value": "80+",
        "label": "score to auto-send"
      },
      {
        "value": "2",
        "label": "scoring axes"
      }
    ],
    "result": "Discover → score → pitch → send pipeline runs end-to-end, compliance built in",
    "techStack": [
      "Next.js 16",
      "React 19",
      "TypeScript",
      "Drizzle ORM",
      "Resend"
    ],
    "status": "Built",
    "url": null,
    "tier": "standard"
  },
  {
    "slug": "jarvis",
    "name": "Jarvis",
    "category": "AI Agent",
    "tagline": "An Iron Man–style assistant that builds holograms",
    "description": "A voice-driven personal AI assistant with a holographic fabrication engine. It sees through a camera with Gemini vision and runs on an always-on wake word. Hand it a reference image and it turns that into a 3D hologram, then designs and renders its own builds. Each result gets compared against the reference, with fixes hot-swapped in a self-correction loop.",
    "problem": "Voice assistants stop at conversation. They can't see what's in front of them. They can't build anything you can inspect, and they have no way to check whether their own output is actually correct.",
    "approach": "A FastAPI backend ties three layers together. The input layer stays always-on: a wake word opens a voice channel, and a camera feed goes to Gemini vision so the assistant can reason about what it sees. The graphics layer renders in the browser on Three.js/WebGL. Its Hologram Deconstructor takes a reference image and uses Depth Anything V2 in-browser to lift it into a depth-mapped 3D hologram, which is the Relief engine. The key build is the Fabrication Engine. Rather than treating schematics as flat pictures, it generates them as JARVIS-designed 3D builds described in a rich geometry language, assembling roughly 12 to 30 parts per component. What makes it more than a renderer is the Iron Man self-correction loop. The engine renders its own build, sends that render back through Gemini vision to compare against the reference, then hot-swaps fixes and re-renders. A REFINE control triggers another pass on demand.",
    "outcome": "Built and working. The assistant sees through a camera, deconstructs a reference image into a 3D hologram, then designs and renders its own multi-part 3D build. From there it critiques and corrects that build against the reference in a closing loop. The self-correction loop renders, critiques, and refines its own 3D builds.",
    "highlights": [
      "Always-on wake word and voice, FastAPI backend with Gemini vision",
      "Hologram Deconstructor plus Relief engine using Depth Anything V2, in-browser",
      "Fabrication Engine builds schematics as 3D geometry, 12-30 parts per component",
      "Iron Man self-correction loop: render the build, vision-critique against the reference, refine",
      "REFINE control re-runs the render-compare-fix pass on demand",
      "Browser graphics on Three.js/WebGL, no server round-trip for rendering"
    ],
    "metrics": [
      {
        "value": "12-30",
        "label": "parts per component"
      }
    ],
    "result": "Self-correction loop renders, critiques, and refines its own 3D builds",
    "techStack": [
      "Python",
      "FastAPI",
      "Gemini",
      "Three.js",
      "Depth Anything V2",
      "WebGL"
    ],
    "status": "Built",
    "url": null,
    "tier": "flagship"
  },
  {
    "slug": "intern-agent",
    "name": "Intern Agent",
    "category": "AI Agent",
    "tagline": "An autonomous AI internship hunter",
    "description": "An autonomous agent that runs internship hunting from start to finish. It scrapes 8+ job boards, scores each opening against your résumé, writes personalised cover letters, and manages the whole application pipeline with tracking and analytics.",
    "problem": "Internship hunting is a high-volume grind. The same listings show up across LinkedIn, Indeed, Glassdoor, Handshake, and WayUp, and every one wants a tailored cover letter, a manual apply, and a follow-up you forget to send. Do it by hand and you either apply to a handful of roles well or to a lot of roles badly.",
    "approach": "The agent is a staged Python pipeline: scrape, score, apply, follow-up. Each opening moves through as a tracked record in SQLite. Scrapers pull from 8+ boards (LinkedIn, Indeed, Glassdoor, Handshake, WayUp), then a match-scoring step ranks every role against the résumé using demand analysis and skills-gap detection, so the highest-fit listings float to the top. The Claude API writes a personalised cover letter per role with A/B/C tone variants, and Playwright drives the actual submission. Both sit behind an outbox and approvals, so nothing goes out unreviewed. A Streamlit interface ties the loop together with pipeline tracking and analytics, and follow-ups get scheduled off the same record.",
    "outcome": "Built and shipping at 3,200+ lines. It's a complete scrape → score → apply → follow-up pipeline with an outbox, an approval gate, Playwright auto-apply, and follow-up scheduling, all surfaced through a Streamlit dashboard with tracking and analytics.",
    "highlights": [
      "Scrapes 8+ boards: LinkedIn, Indeed, Glassdoor, Handshake, WayUp",
      "Match scoring against your résumé using demand analysis and skills-gap detection",
      "AI cover-letter generation with A/B/C tone variants via the Claude API",
      "Playwright auto-apply behind an outbox and approval gate",
      "One Streamlit dashboard for tracking, analytics, and scheduled follow-ups",
      "SQLite-backed records carry each opening from scrape through follow-up"
    ],
    "metrics": [
      {
        "value": "3,200+",
        "label": "lines shipped"
      },
      {
        "value": "8+",
        "label": "job boards scraped"
      },
      {
        "value": "A/B/C",
        "label": "cover-letter tone variants"
      }
    ],
    "result": "3,200+ lines shipping a full scrape → score → apply → follow-up pipeline",
    "techStack": [
      "Python",
      "Streamlit",
      "SQLite",
      "Playwright",
      "Claude API"
    ],
    "status": "Built",
    "url": null,
    "tier": "standard"
  },
  {
    "slug": "mission-control",
    "name": "Mission Control",
    "category": "Developer Tool",
    "tagline": "A local command center for your whole project fleet",
    "description": "A local macOS command center that watches an entire project fleet from one pane of glass. Live status lights, KPI sparklines, git freshness, uptime, and launchd schedule checks all stream in from a 24/7 Node daemon, rendered behind a NASA-ops interface.",
    "problem": "Run a dozen projects at once and their health scatters across terminals, cron logs, and git checkouts. You find out something broke long after it actually did. There's no single place to glance at and know which projects are fresh, running, and on schedule.",
    "approach": "A 24/7 Node daemon runs real probes against each project: git freshness, uptime, launchd schedule state, KPIs. It writes the results to a node:sqlite telemetry store. The Next.js 15 / React 19 front end, written in TypeScript, renders them as a read-only Fleet Grid and pushes updates over SSE every 30 seconds. Boot starts with an env safety gate, a self-test that fails closed if it detects a secret leak before the daemon comes up. On top of that sits the M3 hole-finder. It runs suggest-only audit agents that spawn the trusted Claude CLI in read-only mode and hand back findings instead of touching code.",
    "outcome": "Built and running locally. It monitors 12 projects in one Fleet Grid with live status lights and KPI sparklines. The audit agents have already surfaced 5 real findings, proven on the troy project, with no write access to any monitored repo.",
    "highlights": [
      "Read-only Fleet Grid with live status lights and KPI sparklines",
      "Git freshness, uptime, and launchd schedule probes every 30s",
      "24/7 Node daemon writes telemetry to a node:sqlite store, streamed over SSE",
      "Env safety gate: boot self-test fails closed on secret leaks",
      "Suggest-only audit agents spawn a read-only Claude CLI and return findings",
      "Monitors 12 projects; audit agents surfaced 5 real findings on troy"
    ],
    "metrics": [
      {
        "value": "12",
        "label": "projects monitored"
      },
      {
        "value": "5",
        "label": "real findings surfaced"
      },
      {
        "value": "30s",
        "label": "probe interval"
      },
      {
        "value": "24/7",
        "label": "telemetry daemon"
      }
    ],
    "result": "Running locally — monitors 12 projects; audit agents surfaced 5 real findings",
    "techStack": [
      "Next.js 15",
      "React 19",
      "Node.js",
      "node:sqlite",
      "SSE",
      "TypeScript"
    ],
    "status": "Built",
    "url": null,
    "tier": "standard"
  },
  {
    "slug": "stock-trader",
    "name": "Stock Trader V7",
    "category": "Quant / Trading",
    "tagline": "Sector rotation, running live and fully hands-off",
    "description": "A systematic equity engine that runs leveraged sector rotation off momentum and volatility targeting. The V7 \"PUSH-20\" strategy has traded live on an Alpaca paper account since June 9, 2026. It places its own orders on a schedule, tracks execution and slippage, and runs with no human in the loop.",
    "problem": "Discretionary trading is inconsistent and eats your time. Most \"systems\" never actually run unattended. They live in a backtest notebook and die there. The hard part was never the signal. It's getting a strategy to execute itself every day without someone babysitting it.",
    "approach": "The engine ranks sectors by momentum, sizes positions with volatility targeting, then applies leverage. That's the \"PUSH-20\" tuning, which produced 20.7% CAGR against a −30% max drawdown across the 2005–2024 backtest. Execution runs as a two-speed loop. A fast 60-second cycle checks open positions and order fills; a separate daily cycle recomputes signals and rotates the book. The whole thing is wired to launchd, so it wakes the Mac and runs on its own schedule, hands-off, with a live HUD dashboard for watching fills and slippage. Under the hood it's Python on pandas and numpy, yfinance for data, the Alpaca API for order execution, and pytest covering the logic.",
    "outcome": "A leveraged sector-rotation engine, live on an Alpaca paper account since June 9, 2026. It runs fully hands-off on a launchd schedule, with paper equity at $103.5k. The backtest shows 20.7% CAGR against a −30% max drawdown over 2005–2024, and now it trades itself daily: 60-second position checks, daily signal rotation, real order execution, slippage tracking.",
    "highlights": [
      "20.7% CAGR / −30% max drawdown in backtest (2005–2024)",
      "Live on an Alpaca paper account since Jun 9, 2026",
      "Two-speed loop: 60-second position checks plus daily signal cycles",
      "Fully hands-off via launchd, with the Mac waking itself on schedule",
      "Live HUD dashboard tracking fills and slippage",
      "Paper equity at $103.5k"
    ],
    "metrics": [
      {
        "value": "20.7%",
        "label": "CAGR (backtest)"
      },
      {
        "value": "−30%",
        "label": "max drawdown (backtest)"
      },
      {
        "value": "60s",
        "label": "position-check loop"
      },
      {
        "value": "$103.5k",
        "label": "paper equity"
      }
    ],
    "result": "Live & hands-off on Alpaca paper since Jun 2026 — 20.7% CAGR backtest",
    "techStack": [
      "Python",
      "pandas",
      "numpy",
      "yfinance",
      "Alpaca API",
      "pytest"
    ],
    "status": "Live",
    "url": null,
    "tier": "flagship"
  },
  {
    "slug": "futures-trader",
    "name": "NQ Futures Quant Suite",
    "category": "Quant / Trading",
    "tagline": "Two-sleeve NQ systems, backtested across 26 years",
    "description": "A systematic NQ futures system built from two complementary sleeves. One is a time-series momentum \"TREND\" sleeve; the other is a mean-reversion dip-catcher. It ships with a daily signal tool and a full validation stack, and I backtested it across 26 years of daily bars. Backtest only, with no real capital deployed.",
    "problem": "Discretionary futures trading is inconsistent and hard to sustain. A single strategy also tends to bleed in the regimes it wasn't designed for. Trend systems chop sideways in range-bound markets, and mean-reversion systems get run over in strong trends. The harder problem is trust. Most \"systems\" are never validated rigorously enough to believe their backtest.",
    "approach": "Two sleeves run side by side so each covers the other's weak regime. The TREND sleeve is time-series momentum on the NQ, sized at 5x, posting 19.3% CAGR against a −43% max drawdown at a ~40% win rate. That's typical of trend-following, where a few large wins carry many small losses. The DIP-CATCHER mean-reversion sleeve buys oversold pullbacks only above the 200-day SMA, triggering on RSI(2) ≤ 10, three down days, or low-IBS dips, sized at 2–3x MNQ. It runs a high-hit-rate profile around 70% win and 8–16% CAGR. Blended, the two run at ~21.8% CAGR. The whole thing sits on a pure-stdlib backtest engine in Python with NumPy, Pandas, and PyArrow. I validated it four ways: Monte-Carlo resampling, walk-forward testing, cost-stress, and an 1,800-config parameter frontier to confirm the edge isn't a single lucky setting.",
    "outcome": "A working two-sleeve NQ system with a from-scratch backtest engine and a ready-to-trade daily signal tool. I validated it across a 26-year (2000–2026) cost-stressed backtest at ~21.8% blended CAGR. It stays backtest only, with no real capital deployed.",
    "highlights": [
      "TREND sleeve: 19.3% CAGR / −43% max drawdown, ~40% win at 5x",
      "DIP-CATCHER mean reversion: ~70% win, 8–16% CAGR at 2–3x MNQ",
      "Entries on RSI(2) ≤ 10, three down days, or low-IBS dips above the 200-SMA",
      "Backtested 2000–2026, 26 years of daily NQ bars, net of costs",
      "Validated with Monte-Carlo, walk-forward, cost-stress, and an 1,800-config frontier",
      "Pure-stdlib backtest engine plus a ready-to-trade daily signal tool"
    ],
    "metrics": [
      {
        "value": "~21.8%",
        "label": "Blended CAGR (backtest)"
      },
      {
        "value": "~70%",
        "label": "Mean-reversion win rate"
      },
      {
        "value": "26 yrs",
        "label": "Backtest span (2000–2026)"
      },
      {
        "value": "1,800",
        "label": "Config frontier tested"
      }
    ],
    "result": "~21.8% blended CAGR across a 26-year, cost-stressed backtest",
    "techStack": [
      "Python",
      "NumPy",
      "Pandas",
      "PyArrow"
    ],
    "status": "Backtest only",
    "url": null,
    "tier": "standard"
  },
  {
    "slug": "shanty-realestate",
    "name": "Shanty Soerjono — Realtor Site",
    "category": "Website",
    "tagline": "A live, motion-driven probate-realtor platform",
    "description": "A Next.js marketing site for a probate and trust specialist realtor serving LA County and Orange County. The homepage leans hard into motion: parallax, a 3D house model, constellation effects. Behind it runs an inbound funnel that turns visitors into leads through forms, gated content, and an AI probate assistant. Live in production.",
    "problem": "A probate and trust specialist realtor needed real inbound leads in a niche most agents ignore. A brochure site wouldn't cut it. Probate sellers show up mid-process with specific questions, so the site had to answer those questions and route the lead into follow-up instead of just listing a phone number.",
    "approach": "Built on Next.js 16 and React 19. The homepage motion layers Framer Motion parallax, a Three.js 3D home, and constellation effects. The AI probate assistant runs on Gemini with an automatic NIM fallback, so a model outage degrades to a backup provider rather than a dead chat. Lead capture is decoupled from any single CRM. A form submission fans out to env-gated Resend, HubSpot, Brevo, and Sheets sinks, so each destination toggles on with its own credentials and missing keys skip that sink instead of breaking the form. Captured leads drop into automated nurture sequences split by intent across probate, buyer, and attorney paths. Deployment runs on Vercel with DNS pointed from GoDaddy.",
    "outcome": "Shipped and live in production at shanty-realestate.com since June 2026. The motion-rich site, the Gemini-with-NIM-fallback probate assistant, the multi-sink lead funnel across Resend, HubSpot, Brevo, and Sheets, and the three intent-based nurture sequences are all running on a real business domain.",
    "highlights": [
      "AI probate assistant on Gemini with an automatic NIM fallback",
      "Lead capture fans out to env-gated Resend, HubSpot, Brevo & Sheets sinks",
      "Framer Motion parallax, a Three.js 3D home, and constellation effects",
      "Automated nurture sequences split into probate, buyer, and attorney paths",
      "Next.js 16 / React 19, deployed on Vercel with GoDaddy DNS",
      "Live in production on the realtor's real domain since June 2026"
    ],
    "metrics": [],
    "result": "Live in production at shanty-realestate.com since Jun 2026",
    "techStack": [
      "Next.js 16",
      "React 19",
      "Framer Motion",
      "Three.js",
      "Tailwind",
      "Gemini"
    ],
    "status": "Live",
    "url": "https://shanty-realestate.com",
    "tier": "flagship"
  },
  {
    "slug": "troy-njrotc-site",
    "name": "Troy NJROTC Warriors",
    "category": "Website",
    "tagline": "A cinematic, naval-inspired redesign for a JROTC unit",
    "description": "A static redesign of troynjrotc.org for a high-school Navy JROTC program. The front door is a WebGL hero scene: a fresnel energy core, a wireframe globe, orbiting gyroscope rings, and a parallax starfield, all moving under smooth scroll animation. A dark navy, red, and white design system carries that look across 30+ pages.",
    "problem": "A JROTC unit's site has to carry a large, sprawling program. That means the core unit plus a dozen-plus competitive teams, all while still reading like a naval organization. Most templated school sites manage neither. They flatten everything into the same generic pages and feel nothing like the unit they represent.",
    "approach": "The hero is a Three.js WebGL scene built around a custom fresnel shader. The energy core glows brighter at its edges, where the view angle grazes the surface, and it's wrapped by a wireframe globe, orbiting gyroscope rings, and a parallax particle starfield for depth. Motion runs on Lenis for smooth scroll, feeding GSAP ScrollTrigger so animations fire as sections enter the viewport instead of on a timer. The whole thing is static JavaScript with no build step or backend. That lets the 30+ pages, including 12+ dedicated competitive-team pages for CyberPatriot, robotics, and StellarXplorers, share one navy/red/white design system in Cinzel and Oswald rather than getting squeezed into a single template.",
    "outcome": "Built and ready to ship: 30+ pages with the custom WebGL hero and per-team sections. Not yet deployed.",
    "highlights": [
      "Three.js WebGL hero with a custom fresnel core, wireframe globe, orbit rings, and starfield",
      "GSAP ScrollTrigger driven by Lenis for scroll-triggered animation",
      "12+ dedicated competitive-team pages (CyberPatriot, robotics, StellarXplorers)",
      "Navy / red / white design system in Cinzel and Oswald typography",
      "Fully static JavaScript, with no build step and no backend",
      "30+ pages sharing one consistent naval design language"
    ],
    "metrics": [
      {
        "value": "30+",
        "label": "pages"
      },
      {
        "value": "12+",
        "label": "competitive-team pages"
      }
    ],
    "result": "30+ pages with a custom WebGL hero, built and ready to ship",
    "techStack": [
      "Three.js",
      "GSAP",
      "ScrollTrigger",
      "Lenis",
      "WebGL",
      "JavaScript"
    ],
    "status": "Built",
    "url": null,
    "tier": "standard"
  },
  {
    "slug": "mintset",
    "name": "MINTSET",
    "category": "Content Engine",
    "tagline": "A weekly autopilot factory for finance reels",
    "description": "A fully autonomous content engine for finance storytelling reels. AI writes the scripts, a deterministic Remotion factory renders them, and scheduled crons post to @mint._.set with no human in the loop. It was built for a creator who needs to publish daily short-form without doing the daily work.",
    "problem": "Posting short-form video consistently is a grind, and it burns creators out within weeks. The daily scripting, voiceover, editing, captioning, and publishing never stop. MINTSET takes the human out of that loop so the cadence holds without anyone showing up every day.",
    "approach": "The core is a deterministic \"V7 factory.\" Each reel is defined by a JSON spec, and the same locked Remotion template renders it into a unique reel: ElevenLabs voiceover, 8 FLUX-generated images, beat-synced caption phrases, and generated code. Output stays repeatable but never comes out identical. Two launchd crons run the whole machine. A Sunday 5pm job kicks off a multi-agent batch that writes the next week's 7 scripts and renders all 7 up front. Then a daily 5pm cron posts one pre-rendered reel through the Buffer API with no approval gate. A ManyChat funnel sits downstream of the posts to capture interest.",
    "outcome": "Live and running hands-off. Every Sunday it writes and renders the week's seven reels. Every day a cron publishes one to @mint._.set as 1 TikTok plus 5 Instagram parts. Script to publish, with no human in the loop.",
    "highlights": [
      "Weekly multi-agent batch writes 7 human-scorable scripts every Sunday",
      "Deterministic V7 factory: one locked template, unique VO, music, and imagery per reel",
      "JSON-spec pipeline running ElevenLabs TTS, 8 FLUX images, beat-synced captions, and generated code",
      "Two launchd crons: Sunday renders all 7, daily posts one with no approval gate",
      "Publishes to @mint._.set as 1 TikTok plus 5 Instagram parts daily",
      "ManyChat funnel downstream of posts to capture interest"
    ],
    "metrics": [
      {
        "value": "7",
        "label": "scripts written & rendered weekly"
      },
      {
        "value": "8",
        "label": "FLUX images per reel"
      },
      {
        "value": "1 + 5",
        "label": "TikTok + IG parts posted daily"
      }
    ],
    "result": "Live & autonomous — 1 TikTok + 5 Instagram parts posted daily, hands-off",
    "techStack": [
      "Remotion",
      "React",
      "Node.js",
      "ElevenLabs",
      "FLUX",
      "Buffer API"
    ],
    "status": "Live",
    "url": null,
    "tier": "flagship"
  },
  {
    "slug": "finance-book",
    "name": "Money, Finally Explained",
    "category": "Content Engine",
    "tagline": "Personal finance from zero, for 16–24 year-olds",
    "description": "A 150-page personal-finance book for 16–24 year-olds that teaches money from a first paycheck all the way to retirement. It reads at an 8th-grade level and never drops jargon without explaining it. Roth IRA and 401(k) get full step-by-step walkthroughs, and three recurring characters keep the lessons grounded in real situations.",
    "problem": "Most beginner finance content assumes you already get jargon, charts, and tax brackets. So the people who need the basics most, teens and young adults staring down a first paycheck, lose the thread early and quit. This book starts from zero and stays readable the whole way through.",
    "approach": "I wrote the manuscript in Markdown at an 8th-grade reading level, then built clean EPUB3 and PDF editions from that one source. The charts (tax brackets, compounding, market history) are generated with Matplotlib, so the visuals match the text and rebuild straight from the data. A Python toolchain holds the manuscript, charts, and outputs together. Three recurring characters and documented real stories, Ronald Read, Buffett, the 2008 crash, give the financial concepts a narrative spine rather than a pile of isolated definitions.",
    "outcome": "Complete and built. 26 chapters and 99k+ words, with EPUB and PDF production builds ready to go. The full manuscript, the charts, and both editions are finished and generated from a single source.",
    "highlights": [
      "26 chapters, 99k+ words, fully written and built",
      "EPUB + PDF production builds ready from a single source",
      "Teaches how to read charts, tax brackets and compounding visually",
      "Step-by-step Roth IRA and 401(k) walkthroughs from zero",
      "Three recurring characters anchor concepts in real situations",
      "Real documented stories: Ronald Read, Buffett, the 2008 crash"
    ],
    "metrics": [
      {
        "value": "26",
        "label": "chapters"
      },
      {
        "value": "99k+",
        "label": "words written"
      },
      {
        "value": "150",
        "label": "pages"
      },
      {
        "value": "2",
        "label": "editions (EPUB / PDF)"
      }
    ],
    "result": "Complete — 26 chapters / 99k+ words, EPUB + PDF builds ready",
    "techStack": [
      "Python",
      "Markdown",
      "EPUB3",
      "PDF",
      "Matplotlib charts"
    ],
    "status": "Built",
    "url": null,
    "tier": "standard"
  },
  {
    "slug": "fintwit-dashboard",
    "name": "Investor Alpha Hub",
    "category": "SaaS Product",
    "tagline": "Track institutional money moves in real time",
    "description": "A financial-intelligence dashboard that puts institutional money moves in front of retail investors. Hedge funds, politicians, insiders, and sovereign wealth funds, all in one place. You get real-time catalysts and multi-source sentiment, plus a multi-gate safety framework that cross-checks signals before you act on them.",
    "problem": "Retail investors who want to follow \\\"smart money\\\" end up stitching together scattered 13F filings, congressional disclosures, insider forms, and sovereign-fund reports by hand. Any single source can run late, get noisy, or be flat-out wrong. Nothing consolidates the view, shows you who's moving, and forces you to verify a signal before you trade on it.",
    "approach": "The dashboard pulls activity from 9 market data sources into one feed. It covers 28+ tracked investors sorted into 7 categories: hedge funds, politicians, insiders, sovereign wealth funds, and more. Two checks sit on top of that feed. Multi-source sentiment keeps any single feed from driving the read, and a multi-gate safety validation framework cross-verifies a signal across gates before it ever surfaces as actionable. The front end is static, built in vanilla JS, HTML5, and CSS3 with no framework. The OLED dark-mode interface uses Fira Sans for the UI and Fira Code for tabular figures, held at 4.5:1 contrast so dense rows of numbers stay legible at a glance.",
    "outcome": "Shipped and Built. The dashboard tracks 28+ investors across 7 categories from 9 live data sources. Real-time catalysts run alongside multi-source sentiment and the multi-gate safety checks, all in a single OLED dark interface.",
    "highlights": [
      "Tracks 28+ investors across 7 categories in one feed",
      "Real-time catalysts pulled from 9 market data sources",
      "Multi-source sentiment so no single feed drives the read",
      "Multi-gate safety validation cross-checks signals before action",
      "OLED dark UI, Fira Code tabular figures, 4.5:1 contrast",
      "Static vanilla-JS front end, no framework dependencies"
    ],
    "metrics": [
      {
        "value": "28+",
        "label": "investors tracked"
      },
      {
        "value": "7",
        "label": "investor categories"
      },
      {
        "value": "9",
        "label": "live data sources"
      },
      {
        "value": "4.5:1",
        "label": "UI contrast ratio"
      }
    ],
    "result": "Tracks 28+ investors across 7 categories from 9 live data sources",
    "techStack": [
      "HTML5",
      "CSS3",
      "Vanilla JS",
      "Fira Sans",
      "Fira Code"
    ],
    "status": "Built",
    "url": null,
    "tier": "standard"
  }
];

/* ============================================================
   TESTIMONIALS — fill these in with REAL client quotes to make
   the "What clients say" section appear (hidden while empty).
   Example shape:
   { quote: "Nicholas shipped our MVP in 5 weeks, solo.", name: "Shanty Soerjono",
     title: "Probate & Trust Realtor", url: "https://shanty-realestate.com" }
   ============================================================ */
window.NS_TESTIMONIALS = [
  // { quote: "", name: "", title: "", url: "" },
];
