// Regenerates sitemap.xml from the static pages + every project in data.js.
// The hand-maintained list drifted (12 case pages were missing); this keeps it honest.
// Run after editing data.js:  node gen-work.mjs && node gen-cases.mjs && node gen-sitemap.mjs
import fs from 'node:fs';

const window = {};
eval(fs.readFileSync('data.js', 'utf8')); // sets window.NS_PROJECTS

const SITE = 'https://nicholasnyaung.com/';
const today = new Date().toISOString().slice(0, 10);
const PAGES = [
  ['', 1], ['work.html', 0.9], ['services.html', 0.8], ['about.html', 0.8],
  ['writing.html', 0.7], ['contact.html', 0.7], ['now.html', 0.6], ['uses.html', 0.6],
];

const url = (path, priority) => `  <url>
    <loc>${SITE}${path}</loc>
    <lastmod>${today}</lastmod>
    <changefreq>monthly</changefreq>
    <priority>${priority}</priority>
  </url>`;

const body = [
  ...PAGES.map(([p, pr]) => url(p, pr)),
  ...window.NS_PROJECTS.map((p) => url(`work-${p.slug}.html`, 0.7)),
].join('\n');

fs.writeFileSync('sitemap.xml', `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by gen-sitemap.mjs — do not hand-edit. -->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${body}
</urlset>
`);
console.log('sitemap.xml regenerated —', PAGES.length + window.NS_PROJECTS.length, 'URLs');
